Repository onflow/flow-go, pull requests merged in 2020-12, with the labels that each got.

#197 Update to Cadence v0.11.2 and Go SDK v0.13.0
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
Labels: Breaking Change

#146 Extend `read-badger` database toolset
  cmd/util/cmd/common/print.go
  cmd/util/cmd/read-badger/cmd/blocks.go
  cmd/util/cmd/read-badger/cmd/chunk_data_pack.go
  cmd/util/cmd/read-badger/cmd/cluster_blocks.go
  cmd/util/cmd/read-badger/cmd/collections.go
  cmd/util/cmd/read-badger/cmd/commits.go
  cmd/util/cmd/read-badger/cmd/epoch_commit.go
  cmd/util/cmd/read-badger/cmd/epoch_statuses.go
  cmd/util/cmd/read-badger/cmd/events.go
  cmd/util/cmd/read-badger/cmd/guarantees.go
  cmd/util/cmd/read-badger/cmd/receipts.go
  cmd/util/cmd/read-badger/cmd/results.go
  cmd/util/cmd/read-badger/cmd/root.go
  cmd/util/cmd/read-badger/cmd/seals.go
  cmd/util/cmd/read-badger/cmd/transaction_results.go
  cmd/util/cmd/read-badger/cmd/transactions.go
  storage/all.go
  storage/badger/all.go
Labels: Feature, Improvement

#189 Update `Finalize` to copy private keys from `Keygen` to output folder
  cmd/bootstrap/cmd/copy.go
  cmd/bootstrap/cmd/finalize.go
Labels: Improvement

#158 Storage fees: include key size in storage used
  engine/execution/state/bootstrap/bootstrap_test.go
  fvm/state/accounts.go
  fvm/state/accounts_test.go
  utils/unittest/execution_state.go
Labels: Feature

#219 Fix accounts
  fvm/state/accounts.go
  fvm/state/accounts_test.go
Labels: Bugfix

#220 Fix accounts
  fvm/state/accounts.go
  fvm/state/accounts_test.go
Labels: Bugfix

#215 Storage Fees - Storage Used
  cmd/util/cmd/execution-state-extract/execution_state_extract.go
  cmd/util/ledger/migrations/accounts.go
  cmd/util/ledger/migrations/multiple_contract_migration.go
  cmd/util/ledger/migrations/storage_fees_migration.go
  cmd/util/ledger/migrations/storage_reporter.go
  cmd/util/ledger/migrations/utils.go
  engine/execution/state/bootstrap/bootstrap_test.go
  engine/execution/state/delta/delta.go
  engine/execution/state/delta/delta_test.go
  engine/execution/state/delta/view.go
  fvm/env.go
  fvm/state/accounts.go
  fvm/state/accounts_test.go
  fvm/state/ledger.go
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  utils/unittest/execution_state.go
Labels: Feature

#128 Adding event limit per transaction
  engine/execution/computation/computer/computer.go
  engine/execution/computation/computer/computer_test.go
  engine/execution/testutil/fixtures.go
  fvm/README.md
  fvm/account.go
  fvm/accounts_test.go
  fvm/astCache_test.go
  fvm/bootstrap.go
  fvm/context.go
  fvm/env.go
  fvm/errors.go
  fvm/fees.go
  fvm/fvm_test.go
  fvm/script.go
  fvm/transaction.go
  fvm/transaction_test.go
  fvm/uuids.go
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  module/chunks/chunkVerifier.go
Labels: Feature

#166 Extend unit tests for Badger storage
  storage/badger/blocks.go
  storage/badger/blocks_test.go
  storage/badger/chunk_data_pack_test.go
  storage/badger/cluster_payloads.go
  storage/badger/cluster_payloads_test.go
  storage/badger/commit_test.go
  storage/badger/epoch_commits_test.go
  storage/badger/epoch_setups_test.go
  storage/badger/epoch_statuses.go
  storage/badger/epoch_statuses_test.go
  storage/badger/events_test.go
  storage/badger/guarantees_test.go
  storage/badger/headers_test.go
  storage/badger/index_test.go
  storage/badger/payloads_test.go
  storage/badger/seals_test.go
  storage/badger/transaction_results_test.go
  storage/badger/transactions.go
  storage/badger/transactions_test.go
  utils/unittest/fixtures.go
Labels: Improvement

#214 Add check to skip copying in `finalize`
  cmd/bootstrap/cmd/finalize.go
Labels: Improvement

#257 Access node grpc metrics
  cmd/access/main.go
  engine/access/access_test.go
  engine/access/ingestion/engine_test.go
  engine/access/rpc/engine.go
  go.mod
  go.sum
Labels: Improvement
