Repository onflow/flow-go, pull requests merged in 2020-11, with the labels that each got.

#104 Update bootstrap process to skip key generation
  cmd/bootstrap/cmd/finalize.go
  model/bootstrap/filenames.go
Labels: Improvement

#129 Update to Cadence v0.10.1
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
Labels: Bugfix

#103 Crypto: BLS-based SPoCK scheme
  crypto/README.md
  crypto/bls.go
  crypto/bls12381_utils.c
  crypto/bls12381_utils.h
  crypto/bls_core.c
  crypto/bls_include.h
  crypto/spock.go
  crypto/spock_test.go
Labels: Feature

#117 Crypto: general updates
  cmd/bootstrap/README.md
  consensus/hotstuff/README.md
  crypto/README.md
  crypto/bls.go
  crypto/bls12381_utils.c
  crypto/bls12381_utils.go
  crypto/bls12381_utils_test.go
  crypto/bls_multisig.go
  crypto/bls_test.go
  crypto/dkg.go
  crypto/dkg_feldmanvss.go
  crypto/dkg_feldmanvssq.go
  crypto/ecdsa.go
  crypto/ecdsa_test.go
  crypto/hash/hash.go
  crypto/hash/hash_test.go
  crypto/hash/kmac.go
  crypto/hash/types.go
  crypto/random/xorshift.go
  crypto/sign.go
  crypto/sign_test_utils.go
  crypto/thresholdsign.go
  crypto/thresholdsign_test.go
  crypto/types.go
  go.mod
  go.sum
  integration/go.sum
  model/encoding/signing_tags.go
  state/protocol/seed/seed.go
Labels: Feature, Improvement

#118 Add `pull` command to Spork process
  cmd/bootstrap/cmd/google.go
  cmd/bootstrap/cmd/pull.go
Labels: Feature, Improvement

#108 Crypto/collection: add signature format check to collection nodes
  access/errors.go
  access/validator.go
  crypto/bls.go
  crypto/ecdsa.go
  crypto/ecdsa_test.go
  crypto/sign.go
  engine/collection/ingest/engine_test.go
  model/flow/transaction.go
  utils/unittest/fixtures.go
Labels: Feature, Improvement

#150 Storage Fees - Expose storage fields to cadence
  fvm/env.go
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
Labels: Feature

#83 NET: Yahya/4864-topic-aware-topology
  Makefile
  cmd/scaffold.go
  engine/channels.go
  engine/channels_test.go
  go.mod
  go.sum
  integration/go.sum
  model/flow/role.go
  model/flow/role_test.go
  network/gossip/libp2p/channel/subscriptionManager.go
  network/gossip/libp2p/mock/subscription_manager.go
  network/gossip/libp2p/network.go
  network/gossip/libp2p/peerManager_test.go
  network/gossip/libp2p/subscriptionManager.go
  network/gossip/libp2p/test/echoengine_test.go
  network/gossip/libp2p/test/epochtransition_test.go
  network/gossip/libp2p/test/meshengine_test.go
  network/gossip/libp2p/test/middleware_test.go
  network/gossip/libp2p/test/testUtil.go
  network/gossip/libp2p/test/topology_test.go
  network/gossip/libp2p/topology/collectionTopology.go
  network/gossip/libp2p/topology/collectionTopology_test.go
  network/gossip/libp2p/topology/fanout.go
  network/gossip/libp2p/topology/helper.go
  network/gossip/libp2p/topology/randPermTopology.go
  network/gossip/libp2p/topology/randPermTopology_test.go
  network/gossip/libp2p/topology/topicBasedTopology.go
  network/gossip/libp2p/topology/topicBasedTopology_test.go
  network/gossip/libp2p/topology/topology.go
  network/gossip/libp2p/topology/topology_test.go
  network/gossip/libp2p/topology/topology_utils.go
  utils/unittest/unittest.go
Labels: Feature

#176 Migrate deferred values of contract values
  cmd/util/ledger/migrations/multiple_contract_migration.go
  cmd/util/ledger/migrations/multiple_contract_migration_test.go
Labels: Bugfix

#172 Ledger: Move trie validation step to only export time
  ledger/complete/ledger.go
  ledger/complete/mtrie/flattener/forest.go
Labels: Improvement
