Repository onflow/flow-go, pull requests merged in 2021-05, with the labels that each got.

#682 Update to Cadence v0.15.1-patch.2
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
Labels: Bugfix

#687 [ledger] further optimize sha3 for amd64
  ledger/common/hash/copy_generic.go
  ledger/common/hash/copy_unaligned.go
  ledger/common/hash/hash_test.go
  ledger/common/hash/keccak.go
  ledger/common/hash/keccak.s
  ledger/common/hash/keccakf.go
  ledger/common/hash/sha3.go
Labels: Performance

#627 Add gzip flag to JSON state exporter
  cmd/util/cmd/exec-data-json-export/ledger_exporter.go
  cmd/util/cmd/export-json-execution-state/cmd.go
  ledger/complete/ledger.go
Labels: Feature

#720 [FVM] Dynamic contract deployment authorization
  fvm/blueprints/contractDeployment.go
  fvm/env.go
  fvm/errors/base.go
  fvm/fvm_test.go
  fvm/handler/contract.go
  fvm/handler/contract_test.go
  fvm/handler/programs.go
  fvm/metrics.go
  fvm/utils/cadenceValues.go
Labels: Improvement

#746 Update to Cadence v0.16.1
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
Labels: Bugfix

#747 Update to Cadence v0.16.1
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
Labels: Bugfix

#748 [Ledger] Fix a typo in copy function
  ledger/common/hash/copy_generic.go
Labels: Bugfix

#722 Adjust `bootstrap key` to allow generating `Machine Account` keys
  cmd/bootstrap/cmd/key.go
  cmd/bootstrap/cmd/key_test.go
  cmd/bootstrap/cmd/keys.go
  cmd/bootstrap/run/key_generation.go
  model/bootstrap/filenames.go
  model/bootstrap/node_info.go
  model/encodable/keys.go
Labels: Improvement

#741 Add `machine-account` command to `bootstrap` CLI
  cmd/bootstrap/cmd/keys.go
  cmd/bootstrap/cmd/machine_account.go
  cmd/bootstrap/cmd/machine_account_key.go
  cmd/bootstrap/cmd/machine_account_test.go
  go.sum
  integration/go.sum
Labels: Improvement

#730 Meta-transaction context refactor
  fvm/fvm.go
Labels: Improvement
