Repository onflow/flow-go, pull requests merged in 2021-01, with the labels that each got.

#245 VER: Yahya/4898 handle being unstake verification node
  cmd/verification/main.go
  engine/testutil/mock/nodes.go
  engine/testutil/nodes.go
  engine/verification/finder/concurrency_test.go
  engine/verification/finder/engine.go
  engine/verification/finder/engine_test.go
  engine/verification/test/helper.go
  engine/verification/test/verification_test.go
  engine/verification/utils/fixtures.go
  module/metrics/labels.go
  state/protocol/state.go
  utils/unittest/fixtures.go
Labels: Feature

#207 Crypto: audit updates
  crypto/bls.go
  crypto/bls_core.c
  crypto/bls_include.h
  crypto/bls_multisig.go
  crypto/bls_test.go
  crypto/ecdsa.go
  crypto/ecdsa_test.go
  crypto/hash/hash.go
  crypto/hash/hash_test.go
  crypto/hash/kmac.go
  crypto/hash/sha2.go
  crypto/hash/sha3.go
  crypto/hash/types.go
  crypto/random/xorshift.go
  crypto/sign.go
  crypto/sign_test_utils.go
  crypto/spock.go
  model/encoding/signing_tags.go
  state/protocol/seed/seed.go
Labels: enhancement

#226 Crypto: update the minimum threshold
  cmd/bootstrap/run/dkg.go
  cmd/bootstrap/run/fastkg.go
  consensus/hotstuff/verification/combined_signer.go
  crypto/dkg.go
  crypto/dkg_test.go
  crypto/thresholdsign.go
  crypto/thresholdsign_test.go
  crypto/types.go
  integration/testnet/network.go
  integration/testnet/util.go
  module/signature/threshold.go
  module/signature/threshold_test.go
Labels: enhancement

#271 Update to Cadence v0.12.1 and Go SDK v0.13.0
  cmd/util/ledger/migrations/multiple_contract_migration.go
  cmd/util/ledger/migrations/multiple_contract_migration_test.go
  engine/execution/state/bootstrap/bootstrap_test.go
  fvm/astCache.go
  fvm/astCache_test.go
  fvm/bootstrap.go
  fvm/env.go
  fvm/fvm_test.go
  fvm/metrics.go
  fvm/mock/ast_cache.go
  fvm/script.go
  fvm/transaction.go
  fvm/transaction_test.go
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  integration/tests/common/util.go
  integration/utils/scripts.go
  module/mocks/network.go
  network/mocknetwork/connector.go
  network/p2p/connManager.go
  network/p2p/libp2pConnector.go
  network/p2p/libp2pUtils.go
  network/p2p/middleware.go
  network/p2p/peerManager.go
  network/p2p/peerManager_test.go
  network/test/epochtransition_test.go
  network/topology/README.md
  network/topology/randomizedTopology.go
  network/topology/randomizedTopology_test.go
  network/topology/topicBasedTopology.go
  network/topology/topicBasedTopology.svg
  network/topology/topology.svg
  network/topology/topology_test.go
  storage/mocks/storage.go
  utils/unittest/execution_state.go
  utils/unittest/generator/events.go
Labels: Improvement

#275 Disable event emission for non-transactions and improve FVM errors
  fvm/env.go
Labels: Bugfix

#277 Update to Cadence v0.10.5 and Go SDK v0.12.3
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
Labels: Improvement

#282 Storage Fees - Storage Capacity and Limit
  cmd/util/cmd/read-execution-state/list-accounts/cmd.go
  cmd/util/ledger/migrations/accounts.go
  engine/execution/state/bootstrap/bootstrap.go
  engine/execution/state/bootstrap/bootstrap_test.go
  engine/execution/state/delta/view.go
  engine/execution/testutil/fixtures.go
  fvm/account.go
  fvm/accounts_test.go
  fvm/bootstrap.go
  fvm/context.go
  fvm/env.go
  fvm/errors.go
  fvm/fees.go
  fvm/fvm.go
  fvm/fvm_test.go
  fvm/mock/ast_cache.go
  fvm/script.go
  fvm/state/accounts.go
  fvm/state/accounts_test.go
  fvm/state/address_generator.go
  fvm/state/ledger.go
  fvm/state/state.go
  fvm/state/state_test.go
  fvm/state/uuids.go
  fvm/transaction.go
  fvm/transactionSequenceNum.go
  fvm/transactionStorageLimiter.go
  fvm/transactionStorageLimiter_test.go
  go.mod
  go.sum
  integration/go.sum
  module/mocks/network.go
  storage/mocks/storage.go
  utils/unittest/execution_state.go
Labels: Feature

#294 Doc update: Hotstuff state machine
  docs/StateMachine_wirth_notifications.png
Labels: Documentation

#319 Move Signatures field from ExecutionResult to ExecutionReceipt
  Makefile
  cmd/bootstrap/run/result.go
  consensus/hotstuff/forks/finalizer/finalizer.go
  engine/execution/ingestion/engine.go
  engine/execution/ingestion/engine_test.go
  engine/verification/match/engine.go
  engine/verification/match/engine_test.go
  engine/verification/utils/fixtures.go
  integration/tests/consensus/sealing_test.go
  model/flow/execution_receipt.go
  model/flow/execution_result.go
  model/flow/incorporated_result_test.go
  module/chunks/chunkVerifier_test.go
  module/chunks/chunk_assigner_test.go
  module/forest/leveled_forrest.go
  module/forest/leveled_forrest_test.go
  module/forest/mock/vertex.go
  module/forest/vertex.go
  module/mempool/mock/result_forest.go
  module/mempool/stdmap/result_data_packs_test.go
  state/protocol/badger/mutator_test.go
  storage/badger/receipts_test.go
  utils/unittest/fixtures.go
Labels: Bugfix

#321 Incorporated Receipts form tree (without gaps)
  cmd/consensus/main.go
  consensus/integration/nodes_test.go
  docs/ExecutionResultTrees.png
  engine/consensus/matching/engine.go
  engine/consensus/matching/engine_test.go
  engine/testutil/mock/nodes.go
  engine/testutil/nodes.go
  model/flow/filter/id/identifier.go
  model/flow/identifier.go
  module/builder/consensus/builder.go
  module/builder/consensus/builder_test.go
  module/mempool/consensus/Fork-Aware_Mempools.md
  module/mempool/consensus/execution_tree.go
  module/mempool/consensus/execution_tree_test.go
  module/mempool/consensus/receipt_equivalence_class.go
  module/mempool/execution_tree.go
  module/mempool/mock/execution_tree.go
  module/mempool/mock/receipts.go
  module/mempool/mock/result_forest.go
  module/mempool/mock/seals.go
  module/mempool/receipts.go
  utils/unittest/chain_suite.go
Labels: Bugfix, Documentation
