Repository onflow/flow-go, pull requests merged in 2021-07, with the labels that each got.

#889 Disable fees for system transactions
  engine/execution/computation/computer/computer.go
  engine/execution/computation/computer/computer_test.go
  engine/execution/computation/execution_verification_test.go
  module/chunks/chunkVerifier.go
Labels: Bugfix

#940 Update to Cadence v0.18.0-patch.5
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
Labels: Bugfix

#936 [Integration] Fixes finalized block height with block state bug
  integration/tests/common/block_state.go
  integration/tests/common/testnet_state_tracker.go
  integration/tests/execution/chunk_data_pack_test.go
  integration/tests/execution/failing_tx_reverted_test.go
  integration/tests/execution/state_sync_test.go
Labels: Bugfix

#942 Fixes bug in `QCClient.Voted` and adds exponential backoff to voting resubmission
  module/epochs/qc_client.go
  module/epochs/qc_voter.go
Labels: bug

#955 Fix tight retry loop when context cancelled in `BaseClient`
  module/epochs/base_client.go
Labels: bug

#1032 Update Godoc for ReadyDoneAware
  module/common.go
Labels: Documentation

#1047 [network, easy] Chores & small bugs in middleware / p2p
  network/middleware.go
  network/mocknetwork/middleware.go
  network/p2p/libp2pNode.go
  network/p2p/libp2pNode_test.go
  network/p2p/middleware.go
Labels: Bugfix

#1037 [Notifier] fix flaky notifier test
  docs/NotifierStateMachine.png
  docs/NotifierUsagePattern.png
  engine/Readme.md
  engine/notifier_test.go
Labels: Bugfix
