Repository onflow/flow-go, pull requests merged in 2021-11, with the labels that each got.

#1583 Fixes a bug where DKG validation would continue after encountering a fatal error
  engine/consensus/dkg/reactor_engine.go
Labels: bug

#912 [crypto] Implement a CSPRNG, replace XORShift+
  consensus/hotstuff/committees/leader/leader_selection.go
  consensus/hotstuff/committees/leader/leader_selection_test.go
  crypto/bls.go
  crypto/bls12381_utils.go
  crypto/bls_multisig.go
  crypto/dkg_jointfeldman.go
  crypto/go.mod
  crypto/go.sum
  crypto/random/chacha20.go
  crypto/random/rand.go
  crypto/random/rand_test.go
  crypto/random/xorshift.go
  crypto/spock.go
  go.mod
  go.sum
  integration/go.sum
  module/chunks/chunk_assigner.go
  network/topology/randomizedTopology.go
Labels: enhancement

#1620 REST: models converters structure
  engine/access/rest/converter.go
  engine/access/rest/models/json.go
  engine/access/rest/rest_api.go
  engine/access/rest/rest_api_server.go
  engine/access/rest/transactions.go
Labels: Improvement

#1627 REST: transactions handlers
  engine/access/rest/converter.go
  engine/access/rest/handlers.go
  engine/access/rest/middleware/common_query_params.go
  engine/access/rest/middleware/common_query_params_test.go
  engine/access/rest/models/json.go
  engine/access/rest/rest_api.go
  engine/access/rest/server.go
  engine/access/rest/transactions.go
  engine/access/rpc/engine.go
Labels: Improvement

#1401 [v0.22] [Storage Migration V6] Add more tests for value converter
  cmd/util/ledger/migrations/storage_v6_test.go
Labels: Improvement

#1646 Transaction model status bugfix
  model/flow/transaction.go
  model/flow/transaction_test.go
Labels: Bugfix

#1680 Update to Go SDK v0.24.0
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
Labels: Improvement

#1681 Update to latest flow-go/crypto, 7b31c98
  go.mod
  integration/go.mod
Labels: Bugfix

#1685 REST: Testing handlers
  engine/access/rest/accounts.go
  engine/access/rest/accounts_test.go
  engine/access/rest/blocks.go
  engine/access/rest/blocks_test.go
  engine/access/rest/collections.go
  engine/access/rest/collections_test.go
  engine/access/rest/converter.go
  engine/access/rest/error.go
  engine/access/rest/execution_result.go
  engine/access/rest/generated/api_accounts.go
  engine/access/rest/generated/api_blocks.go
  engine/access/rest/generated/api_collections.go
  engine/access/rest/generated/api_execution_results.go
  engine/access/rest/generated/api_scripts.go
  engine/access/rest/generated/api_transactions.go
  engine/access/rest/generated/logger.go
  engine/access/rest/generated/routers.go
  engine/access/rest/handler.go
  engine/access/rest/request_decorator.go
  engine/access/rest/scripts.go
  engine/access/rest/scripts_test.go
  engine/access/rest/transactions.go
  engine/access/rest/transactions_test.go
  utils/unittest/fixtures.go
Labels: Improvement
