Repository onflow/flow-go, pull requests merged in 2021-09, with the labels that each got.

#1110 [Storage Migration] Remove broken contracts from storage
  cmd/util/cmd/epochs/cmd/reset.go
  cmd/util/ledger/migrations/storage_v5.go
  cmd/util/ledger/migrations/storage_v5_test.go
Labels: Improvement

#1307 Mainnet quick fix fo address problems of nodes failing to catch up
  module/builder/consensus/builder.go
  module/builder/consensus/builder_test.go
  module/chunks.go
  module/chunks/chunk_assigner.go
  module/validation/seal_validator.go
  state/protocol/badger/snapshot.go
Labels: bug

#1325 Alex/5857 full fix
  module/builder/consensus/builder.go
  module/builder/consensus/builder_test.go
  module/chunks.go
  module/chunks/chunk_assigner.go
  module/validation/seal_validator.go
  module/validation/seal_validator_test.go
  state/protocol/badger/snapshot.go
Labels: bug

#1282 Reduce log level in migration tool
  cmd/util/ledger/migrations/storage_v5.go
Labels: Improvement

#1380 [Storage migration V6] Add storage_index and account storage registers
  cmd/execution/main.go
  cmd/util/ledger/migrations/storage_v6.go
  cmd/util/ledger/migrations/storage_v6_test.go
  cmd/util/ledger/migrations/utils.go
  engine/execution/computation/computer/computer_test.go
  fvm/fvm.go
  fvm/transactionInvocator.go
  fvm/transactionInvocator_test.go
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
Labels: Improvement

#1219 FVM Benchmarking
  fvm/fvm_bench_test.go
Labels: enhancement

#1398 Fix the conversion of fixed point numbers in the Cadence storage v6 state migration
  cmd/util/ledger/migrations/storage_v6.go
Labels: Bugfix
