Repository onflow/flow-go, pull requests merged in 2021-04, with the labels that each got.

#457 [Crypto] improve BLS compression settings in the lib
  crypto/bls.go
  crypto/bls12381_hashtocurve.c
  crypto/bls12381_utils.c
  crypto/bls12381_utils.h
  crypto/bls12381_utils_test.go
  crypto/bls_include.h
  crypto/dkg_core.c
  crypto/thresholdsign_test.go
  crypto/types.go
Labels: Improvement

#505 [Ledger] complete memory trie optimization
  ledger/common/hash.go
  ledger/common/hash_test.go
  ledger/common/proof.go
  ledger/common/sha3.go
  ledger/common/utils/split.go
  ledger/common/utils/utils_test.go
  ledger/complete/ledger_benchmark_test.go
  ledger/complete/mtrie/README.md
  ledger/complete/mtrie/forest.go
  ledger/complete/mtrie/forest_test.go
  ledger/complete/mtrie/node/node.go
  ledger/complete/mtrie/node/node_test.go
  ledger/complete/mtrie/trie/trie.go
  ledger/complete/mtrie/trie/trie_test.go
  ledger/ledger.go
  ledger/partial/ptrie/node.go
  ledger/partial/ptrie/partialTrie.go
  ledger/partial/ptrie/partialTrie_test.go
  ledger/trie.go
Labels: Improvement

#626 [Verification] Chunk data request optimization
  cmd/verification/main.go
  engine/verification/match/engine.go
  engine/verification/match/engine_test.go
Labels: enhancement

#616 Change storage defaults
  cmd/bootstrap/cmd/finalize.go
  engine/execution/state/bootstrap/bootstrap_test.go
  fvm/bootstrap.go
  fvm/fvm_test.go
  integration/testnet/network.go
  utils/unittest/execution_state.go
Labels: Improvement

#639 Update to Cadence v0.14.5 patch.2
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
Labels: Bugfix

#647 Update to Cadence v0.14.5-patch.3
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
Labels: Bugfix

#638 Add state migration for new Cadence storage format v4
  .gitignore
  cmd/util/cmd/execution-state-extract/execution_state_extract.go
  cmd/util/ledger/migrations/storage_v4.go
Labels: Feature

#668 Fix Cadence dependency
  go.mod
  integration/go.mod
Labels: Bugfix

#673 Fix inconsistent RLP encoding for Identity
  model/flow/identity.go
  model/flow/identity_test.go
  state/protocol/inmem/encodable_test.go
Labels: bug
