Repository onflow/flow-go, pull requests merged in 2021-06, with the labels that each got.

#800 skipping pruning of connections which have ongoing one-to-one traffic
  network/p2p/libp2pConnector.go
  network/p2p/libp2pNode.go
  network/p2p/libp2pUtils.go
  network/p2p/ping.go
  network/p2p/protocol.go
Labels: bug

#803 making the peer update interval configurable via a command line argum…
  cmd/scaffold.go
  network/p2p/middleware.go
  network/p2p/peerManager.go
  network/p2p/peerManager_test.go
  network/test/testUtil.go
Labels: enhancement

#832 fix for 5575 - occasional stream reset
  network/p2p/connManager.go
  network/p2p/connManager_test.go
  network/p2p/libp2pConnector.go
  network/p2p/libp2pNode.go
  network/p2p/libp2pUtils.go
  network/p2p/ping.go
Labels: Bugfix

#844 Update to Cadence v0.18.0
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
Labels: Improvement

#598 [Execution] sort chunk data to protect the SPoCK secret entropy
  engine/execution/computation/committer/committer.go
  engine/execution/ingestion/engine.go
  engine/execution/state/state.go
  ledger/complete/ledger.go
  ledger/complete/mtrie/forest.go
  ledger/complete/mtrie/forest_test.go
  ledger/complete/mtrie/trie/trie.go
  ledger/trie.go
  model/flow/chunk.go
Labels: Improvement

#589 [Execution] update the spock secret
  engine/execution/state/delta/delta.go
  engine/execution/state/delta/view.go
  engine/execution/state/delta/view_test.go
  model/flow/ledger.go
Labels: Improvement, Protocol

#850 [Verification] Fixing notifier id at fetcher
  engine/verification/fetcher/engine.go
  engine/verification/fetcher/engine_test.go
Labels: bug

#849 make unicast message timeout configurable via command line argument - fixes bug 5392
  cmd/scaffold.go
  network/p2p/middleware.go
  network/test/testUtil.go
Labels: bug
