Repository onflow/flow-go, pull requests merged in 2021-02, with the labels that each got.

#353 Storage reporter output directory fix
  cmd/util/cmd/execution-state-extract/execution_state_extract.go
  cmd/util/ledger/migrations/storage_reporter.go
Labels: Bugfix

#354 Revert update of v0.13 to Cadence v0.10.6, update to a minimal improvement
  go.mod
  go.sum
Labels: enhancement

#360 Update to Cadence v0.12.6 and Go SDK v0.14.3
  cmd/util/ledger/migrations/multiple_contract_migration.go
  fvm/astCache.go
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
Labels: enhancement

#362 revised scheduling of sealing check
  engine/consensus/matching/engine.go
Labels: enhancement

#371 Update to Cadence v0.12.9
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
Labels: Bugfix

#375 Update to Cadence v0.12.10
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
Labels: Bugfix

#379 Update to Cadence v0.12.11
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
Labels: Bugfix

#444 MAINNET FIX v0.14: require multiple receipts to seal V3
  cmd/consensus/main.go
  engine/common/requester/engine.go
  engine/consensus/matching/engine.go
  engine/consensus/matching/engine_test.go
  utils/unittest/chain_suite.go
Labels: Bugfix

#455 [Ledger] optimize sha3 in the merkle trie
  ledger/common/encoding/encoding.go
  ledger/common/hash.go
  ledger/common/hash_test.go
  ledger/common/proof.go
  ledger/common/sha3.go
  ledger/common/utils/split.go
  ledger/common/utils/utils.go
  ledger/common/utils/utils_test.go
  ledger/complete/mtrie/flattener/trie_test.go
  ledger/complete/mtrie/forest.go
  ledger/complete/mtrie/trie/trie.go
  ledger/partial/ptrie/partialTrie.go
Labels: Improvement

#458 Update to Cadence v0.13.1
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
Labels: Improvement

#392 [Transit] Download Protocol State Snapshot Command
  cmd/bootstrap/transit/main.go
  go.mod
  go.sum
  model/bootstrap/filenames.go
  utils/io/write.go
Labels: Improvement

#461 [Ledger] further optimize custom sha3
  ledger/common/encoding/encoding_test.go
  ledger/common/hash.go
  ledger/common/hash_test.go
  ledger/common/sha3.go
  ledger/common/utils/test.go
  ledger/complete/mtrie/flattener/encoding_test.go
  ledger/complete/mtrie/flattener/forest_test.go
  ledger/complete/mtrie/flattener/iterator_test.go
  ledger/complete/mtrie/flattener/trie_test.go
  ledger/complete/mtrie/forest_test.go
  ledger/complete/mtrie/node/node_test.go
  ledger/complete/mtrie/trie/trie_test.go
  ledger/complete/wal/compactor_test.go
  ledger/complete/wal/encoding_test.go
  ledger/partial/ptrie/partialTrie_test.go
  module/mock/jobs.go
  storage/mock/service_events.go
Labels: Improvement
