Repository onflow/flow-go, pull requests merged in 2022-01, with the labels that each got.

#1801 Update mtrie with some minor fixes and small improvements
  ledger/common/encoding/encoding.go
  ledger/common/proof/proof.go
  ledger/common/utils/testutils.go
  ledger/complete/mtrie/flattener/encoding.go
  ledger/complete/mtrie/forest_test.go
  ledger/complete/mtrie/node/node_test.go
  ledger/complete/mtrie/trie/trie.go
  ledger/complete/mtrie/trie/trie_test.go
  ledger/complete/wal/checkpointer_test.go
  ledger/complete/wal/encoding.go
  ledger/partial/ledger.go
  ledger/partial/ptrie/partialTrie.go
Labels: Improvement

#1838 Preallocate slices in mtrie
  ledger/common/pathfinder/pathfinder.go
  ledger/complete/mtrie/forest.go
  ledger/complete/wal/encoding.go
  ledger/ledger.go
  ledger/partial/ledger.go
  ledger/partial/ptrie/partialTrie.go
  ledger/trie.go
Labels: Performance

#1851 Cadence v0.20.3 patch.2
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
Labels: Bugfix

#1883 Add naive error logging for Access node downstream calls
  engine/access/rpc/backend/backend_accounts.go
  engine/access/rpc/backend/backend_events.go
  engine/access/rpc/backend/backend_scripts.go
  engine/access/rpc/backend/backend_transactions.go
  engine/access/rpc/engine.go
Labels: good first issue, S-Access

#1894 Add logs for MTrie checkpoint file creation
  ledger/complete/wal/checkpointer.go
  ledger/complete/wal/compactor.go
  ledger/complete/wal/wal.go
Labels: Improvement

#1899 Update to Cadence v0.21.0
  cmd/util/ledger/reporters/balance_reporter.go
  engine/execution/state/bootstrap/bootstrap_test.go
  fvm/fvm_test.go
  fvm/programs/programs_test.go
  fvm/transactionInvoker_test.go
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  utils/unittest/execution_state.go
Labels: Improvement

#1870 Optimize Forest.Proofs() and add ValueSizes() to MTrie, Forest, and Ledger
  ledger/common/encoding/encoding.go
  ledger/complete/ledger.go
  ledger/complete/ledger_test.go
  ledger/complete/mtrie/forest.go
  ledger/complete/mtrie/forest_test.go
  ledger/complete/mtrie/trie/trie.go
  ledger/complete/mtrie/trie/trie_test.go
Labels: enhancement, Improvement, Performance

#1875 Fix LedgerGetRegister to avoid caching empty value
  engine/execution/state/state.go
Labels: Bug
