Repository onflow/flow-go, pull requests merged in 2022-08, with the labels that each got.

#2792 [Execution Node] Reuse ledger state in checkpoints for -152GB RAM and -24 minutes
  cmd/bootstrap/run/execution_state.go
  cmd/execution_builder.go
  cmd/util/cmd/exec-data-json-export/ledger_exporter.go
  cmd/util/cmd/execution-state-extract/execution_state_extract.go
  cmd/util/cmd/execution-state-extract/execution_state_extract_test.go
  cmd/util/cmd/export-json-execution-state/cmd.go
  engine/execution/computation/execution_verification_test.go
  engine/execution/computation/manager_test.go
  engine/execution/state/bootstrap/bootstrap_test.go
  engine/execution/state/state_test.go
  engine/testutil/mock/nodes.go
  engine/testutil/nodes.go
  engine/verification/utils/unittest/fixture.go
  fvm/fvm_bench_test.go
  ledger/complete/checkpoint_benchmark_test.go
  ledger/complete/compactor.go
  ledger/complete/compactor_test.go
  ledger/complete/ledger.go
  ledger/complete/ledger_benchmark_test.go
  ledger/complete/ledger_test.go
  ledger/complete/mtrie/forest.go
  ledger/complete/mtrie/forest_test.go
  ledger/complete/mtrie/trieCache.go
  ledger/complete/mtrie/trieCache_test.go
  ledger/complete/wal/checkpointer_test.go
  ledger/complete/wal/compactor.go
  ledger/complete/wal/compactor_test.go
  ledger/complete/wal/fixtures/noopcompactor.go
  ledger/complete/wal/fixtures/noopwal.go
  ledger/complete/wal/triequeue.go
  ledger/complete/wal/triequeue_test.go
  ledger/complete/wal/wal.go
  ledger/partial/ledger_test.go
  module/chunks/chunkVerifier_test.go
Labels: Performance, E&V Team

#1994 [Execution] avoiding double encoding of event key before insertion into the event merkle trie
  model/flow/event.go
  model/flow/event_test.go
  model/flow/identifier.go
Labels: Breaking Change

#2930 [EN Performance] Reduce memory used for ledger.Payload by 32+ GB, eliminate 1+ billion allocs/op, speedup various ops
  cmd/util/ledger/migrations/account_status_migration.go
  cmd/util/ledger/migrations/account_status_migration_test.go
  cmd/util/ledger/migrations/accounts.go
  cmd/util/ledger/migrations/legacy_controller_migration.go
  cmd/util/ledger/migrations/legacy_controller_migration_test.go
  cmd/util/ledger/migrations/prune_migration.go
  cmd/util/ledger/migrations/storage_fees_migration.go
  cmd/util/ledger/migrations/storage_used_update_migration.go
  cmd/util/ledger/migrations/storage_used_update_migration_test.go
  cmd/util/ledger/reporters/atree_reporter.go
  cmd/util/ledger/reporters/fungible_token_tracker.go
  engine/execution/state/state_test.go
  integration/tests/execution/chunk_data_pack_test.go
  ledger/common/pathfinder/pathfinder.go
  ledger/common/pathfinder/pathfinder_test.go
  ledger/common/proof/proof.go
  ledger/common/proof/proof_test.go
  ledger/common/testutils/testutils.go
  ledger/common/utils/utils.go
  ledger/complete/compactor_test.go
  ledger/complete/ledger.go
  ledger/complete/ledger_benchmark_test.go
  ledger/complete/ledger_test.go
  ledger/complete/mtrie/flattener/encoding.go
  ledger/complete/mtrie/flattener/encoding_test.go
  ledger/complete/mtrie/flattener/encoding_v3.go
  ledger/complete/mtrie/flattener/encoding_v3_test.go
  ledger/complete/mtrie/flattener/encoding_v4.go
  ledger/complete/mtrie/flattener/encoding_v4_test.go
  ledger/complete/mtrie/flattener/iterator_test.go
  ledger/complete/mtrie/forest.go
  ledger/complete/mtrie/forest_test.go
  ledger/complete/mtrie/node/node.go
  ledger/complete/mtrie/node/node_test.go
  ledger/complete/mtrie/trie/trie.go
  ledger/complete/mtrie/trie/trie_test.go
  ledger/complete/wal/checkpointer_test.go
  ledger/complete/wal/encoding.go
  ledger/complete/wal/encoding_test.go
  ledger/ledger.go
  ledger/partial/ledger.go
  ledger/partial/ledger_test.go
  ledger/partial/ptrie/partialTrie.go
  ledger/partial/ptrie/partialTrie_test.go
  ledger/trie.go
  ledger/trie_encoder.go
  ledger/trie_encoder_test.go
  ledger/trie_test.go
  module/state_synchronization/execution_data_service_test.go
Labels: Performance, E&V Team

#3013 [FVM] Fix transactions with low gas
  engine/execution/testutil/fixtures.go
  fvm/errors/errors.go
  fvm/executionParameters.go
  fvm/executionParameters_test.go
  fvm/fvm_fuzz_test.go
  fvm/fvm_test.go
  fvm/scriptEnv.go
  fvm/transactionEnv.go
  fvm/transactionInvoker.go
Labels: E&V Team

#3069 [FVM] TEMP Disable sandboxnet storage check
  cmd/scaffold.go
Labels: E&V Team

#3050 [EN Performance] Optimize checkpoint serialization for -37GB operational RAM, -2.7 minutes duration, -19.6 million allocs (50% fewer allocs)
  ledger/complete/mtrie/flattener/iterator.go
  ledger/complete/mtrie/flattener/iterator_test.go
  ledger/complete/wal/checkpointer.go
  ledger/complete/wal/checkpointer_serialization_test.go
Labels: Performance, E&V Team

#3038 Fix race in TestCompactorConcurrency
  ledger/complete/compactor_test.go
Labels: Bugfix, E&V Team

#3071 Fix error logging in script execution - port to master
  cmd/execution_builder.go
Labels: E&V Team

#3059 [FVM] Move HandleRuntimeError to ContractFunctionInvoker
  fvm/contractFunctionInvoker.go
  fvm/contractFunctionInvoker_test.go
  fvm/env.go
  fvm/transactionEnv.go
Labels: E&V Team

#3105 [FVM] Fix account reporter memory limit - master
  cmd/util/ledger/reporters/account_reporter.go
Labels: E&V Team

#3126 [mainnet 19] Hotfix for signer indices decoding
  cmd/access/node_builder/access_node_builder.go
  cmd/observer/node_builder/observer_builder.go
  engine/access/access_test.go
  engine/access/ingestion/engine_test.go
  engine/access/rest_api_test.go
  engine/access/rpc/engine_builder.go
  engine/access/rpc/rate_limit_test.go
  engine/access/secure_grpcr_test.go
Labels: Bug, S-Access, P-High
