Repository onflow/flow-go, pull requests merged in 2022-03, with the labels that each got.

#2084 Replace use of deprecated ioutil funcs in ledger
  ledger/complete/ledger_benchmark_test.go
  ledger/complete/mtrie/flattener/trie_test.go
  ledger/complete/wal/checkpointer.go
  ledger/complete/wal/syncrename_test.go
Labels: Improvement, Performance

#1944 Optimize MTrie checkpoint for speed, memory, and file size
  cmd/util/cmd/checkpoint-list-tries/cmd.go
  cmd/util/cmd/read-execution-state/list-wals/cmd.go
  ledger/common/encoding/encoding.go
  ledger/common/encoding/encoding_test.go
  ledger/complete/checkpoint_benchmark_test.go
  ledger/complete/ledger.go
  ledger/complete/ledger_test.go
  ledger/complete/mtrie/flattener/encoding.go
  ledger/complete/mtrie/flattener/encoding_test.go
  ledger/complete/mtrie/flattener/encoding_v3.go
  ledger/complete/mtrie/flattener/encoding_v3_test.go
  ledger/complete/mtrie/flattener/forest.go
  ledger/complete/mtrie/flattener/forest_test.go
  ledger/complete/mtrie/flattener/iterator.go
  ledger/complete/mtrie/flattener/iterator_test.go
  ledger/complete/mtrie/flattener/storables.go
  ledger/complete/mtrie/flattener/trie.go
  ledger/complete/mtrie/flattener/trie_test.go
  ledger/complete/mtrie/forest.go
  ledger/complete/mtrie/trie/trie_test.go
  ledger/complete/wal/checkpointer.go
  ledger/complete/wal/checkpointer_test.go
  ledger/complete/wal/checkpointer_versioning_test.go
  ledger/complete/wal/compactor_test.go
  ledger/complete/wal/fixtures/noopwal.go
  ledger/complete/wal/test_data/checkpoint.v1
  ledger/complete/wal/test_data/checkpoint.v3
  ledger/complete/wal/wal.go
Labels: Breaking Change, Performance

#2119 [Execution State] Add logging for CPU, RAM, and checkpoint
  cmd/execution/main.go
  go.mod
  go.sum
  integration/go.sum
  ledger/complete/wal/checkpointer.go
  ledger/complete/wal/wal.go
Labels: Improvement

#2096 Fix potential overflow in ledger metrics LatestTrieRegCountDiff() and LatestTrieMaxDepthDiff()
  ledger/complete/mtrie/forest.go
  module/metrics.go
  module/metrics/execution.go
  module/metrics/noop.go
  module/mock/execution_metrics.go
  module/mock/ledger_metrics.go
Labels: Bug

#1631 [FVM] Variable Computation Metering
  engine/execution/computation/computer/computer_test.go
  engine/execution/state/bootstrap/bootstrap_test.go
  fvm/blueprints/fees.go
  fvm/contractFunctionInvocations.go
  fvm/contractFunctionInvoker.go
  fvm/errors/codes.go
  fvm/errors/execution.go
  fvm/fvm.go
  fvm/fvm_bench_test.go
  fvm/fvm_test.go
  fvm/meter/basic/meter.go
  fvm/meter/basic/meter_test.go
  fvm/meter/meter.go
  fvm/meter/noop/meter.go
  fvm/meter/weighted/meter.go
  fvm/meter/weighted/meter_test.go
  fvm/scriptEnv.go
  fvm/state/state.go
  fvm/transactionEnv.go
  fvm/transactionInvoker.go
  fvm/transactionInvoker_test.go
  fvm/transaction_test.go
  fvm/utils/cadenceValues.go
  utils/unittest/execution_state.go
Labels: E&V Team

#2174 Update checkpoint file format version from v4 to v5
  cmd/util/cmd/execution-state-extract/cmd.go
  ledger/complete/mtrie/flattener/encoding_v4.go
  ledger/complete/mtrie/flattener/encoding_v4_test.go
  ledger/complete/wal/checkpointer.go
  ledger/complete/wal/checkpointer_versioning_test.go
  ledger/complete/wal/test_data/checkpoint.v4
Labels: Breaking Change

#2187 Add logs with more system specs
  cmd/execution/main.go
Labels: Improvement

#2223 Reduce default checkpoint distance flag from 40 to 20 to speedup EN startup
  cmd/execution/main.go
Labels: Performance

#2106 [HTTP API] Transaction success status
  Makefile
  README.md
  engine/access/rest/README.md
  engine/access/rest/events_test.go
  engine/access/rest/models/enums.go
  engine/access/rest/models/model_account.go
  engine/access/rest/models/model_account__expandable.go
  engine/access/rest/models/model_account_public_key.go
  engine/access/rest/models/model_aggregated_signature.go
  engine/access/rest/models/model_block.go
  engine/access/rest/models/model_block__expandable.go
  engine/access/rest/models/model_block_event.go
  engine/access/rest/models/model_block_events.go
  engine/access/rest/models/model_block_header.go
  engine/access/rest/models/model_block_payload.go
  engine/access/rest/models/model_block_seal.go
  engine/access/rest/models/model_collection.go
  engine/access/rest/models/model_collection_guarantee.go
  engine/access/rest/models/model_error.go
  engine/access/rest/models/model_event.go
  engine/access/rest/models/model_execution_result.go
  engine/access/rest/models/model_hashing_algorithm.go
  engine/access/rest/models/model_proposal_key.go
  engine/access/rest/models/model_scripts_body.go
  engine/access/rest/models/model_signing_algorithm.go
  engine/access/rest/models/model_transaction.go
  engine/access/rest/models/model_transaction_execution.go
  engine/access/rest/models/model_transaction_result.go
  engine/access/rest/models/model_transaction_signature.go
  engine/access/rest/models/model_transaction_status.go
  engine/access/rest/models/model_transactions_body.go
  engine/access/rest/models/transaction.go
  engine/access/rest/readme.md
  engine/access/rest/transactions_test.go
Labels: S-Access

#2152 [HTTP API] Authorizers bugfix
  engine/access/rest/request/transaction.go
Labels: Bugfix
