Repository onflow/flow-go, pull requests merged in 2022-06, with the labels that each got.

#2549 Fix underflowing of memory metrics difference values
  module/metrics/execution.go
Labels: Bugfix

#2252 Update docs for HTTP API
  cmd/access/README.md
Labels: Documentation

#2593 Update to Cadence v0.24.2-patch.1
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
Labels: Bugfix

#2646 Gracefully handle script result encoding panics
  engine/execution/computation/manager.go
Labels: Bugfix

#2594 [FVM][TEST] Splitting fvm_test.go
  fvm/fvm_blockcontext_test.go
  fvm/fvm_signature_test.go
  fvm/fvm_test.go
Labels: E&V Team

#2655 [Exec] improve result upload/eds tracing
  engine/execution/computation/manager.go
  engine/execution/computation/manager_test.go
  engine/execution/computation/programs_test.go
  module/trace/constants.go
Labels: Improvement

#2580 Add larger buckets for memory estimate metrics
  module/metrics/execution.go
Labels: Improvement

#2353 [FVM] contracts.go refactor
  fvm/handler/contract.go
Labels: E&V Team

#2693 Fix copylocks in TestOnBlockProposal_RemoteOrigin
  engine/consensus/provider/engine_test.go
Labels: Bugfix

#2585 [FVM] remove the use of the legacy controller by the FVM registers
  cmd/util/cmd/execution-state-extract/execution_state_extract.go
  cmd/util/ledger/migrations/legacy_controller_migration.go
  cmd/util/ledger/migrations/legacy_controller_migration_test.go
  cmd/util/ledger/migrations/storage_fees_migration.go
  engine/execution/state/bootstrap/bootstrap_test.go
  fvm/state/accounts.go
  fvm/state/state.go
  fvm/state/state_test.go
  fvm/transactionInvoker_test.go
  utils/unittest/execution_state.go
Labels: Breaking Change
