Repository onflow/flow-go, pull requests merged in 2022-11, with the labels that each got.

#3459 [Baseline Protection] Enables disconnection from disallowed peers
  network/internal/p2pfixtures/fixtures.go
  network/internal/testutils/testUtil.go
  network/p2p/connection/connection_gater.go
  network/p2p/connection/connection_gater_test.go
  network/p2p/connection/connector.go
  network/p2p/connectionGater.go
  network/p2p/mock/connection_gater.go
  network/p2p/p2pbuilder/libp2pNodeBuilder.go
  network/p2p/p2pnode/libp2pNode_test.go
  network/p2p/p2pnode/libp2pStream_test.go
  network/p2p/scoring/subscription_validator_test.go
Labels: S-Network Layer, S-BFT

#3478 fix heap draining bug in synchronization engine
  engine/common/synchronization/request_heap.go
  engine/common/synchronization/request_heap_test.go
Labels: Bugfix

#3627 Shorten bench and make it optional
  .github/workflows/bench.yml
Labels: E&V Team
