Repository onflow/flow-go, pull requests merged in 2022-07, with the labels that each got.

#2530 [FVM] Add missing tests for merging FVM state weights
  fvm/executionParameters.go
  fvm/executionParameters_test.go
  fvm/scriptEnv.go
  fvm/transactionEnv.go
Labels: E&V Team

#2748 [FVM] Benchstat CI improvements
  .github/workflows/bench.yml
  fvm/fvm_bench_test.go
Labels: E&V Team

#2690 [FVM] Don't read context from state on system chunk - port
  engine/execution/computation/computer/computer.go
  engine/execution/computation/computer/computer_test.go
  fvm/context.go
  fvm/fvm_test.go
  fvm/scriptEnv.go
  fvm/transactionEnv.go
Labels: E&V Team

#2531 [FVM] Fix error handling on contract function invocations
  engine/execution/computation/manager_test.go
  fvm/accounts_test.go
  fvm/scriptEnv.go
  fvm/transactionEnv.go
Labels: E&V Team

#2206 Refactor root checkpoint extraction program
  cmd/util/cmd/execution-state-extract/cmd.go
  ledger/complete/wal/checkpointer.go
  model/flow/ledger.go
Labels: Improvement, E&V Team

#2705 [FVM] All service accounts should be bootstrapped with a key
  engine/execution/computation/execution_verification_test.go
  engine/execution/state/bootstrap/bootstrap_test.go
  fvm/bootstrap.go
  model/flow/account_encoder.go
  utils/unittest/execution_state.go
Labels: E&V Team

#2829 fixed decoding error for signer indices at epoch switchover
  consensus/hotstuff/signature/block_signer_decoder.go
  consensus/hotstuff/signature/block_signer_decoder_test.go
Labels: Bugfix, S-Access

#2830 fixed decoding error for signer indices at epoch switchover
  consensus/hotstuff/signature/block_signer_decoder.go
  consensus/hotstuff/signature/block_signer_decoder_test.go
Labels: Bugfix, S-Access

#2608 Bump cadence version
  engine/execution/computation/computer/computer_test.go
  engine/execution/state/bootstrap/bootstrap_test.go
  fvm/errors/errors.go
  fvm/executionParameters_test.go
  fvm/fvm_test.go
  fvm/transactionInvoker_test.go
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  utils/unittest/execution_state.go
Labels: Improvement

#2708 [Execution] Fixed EN debug docker image build failure
  cmd/Dockerfile
Labels: E&V Team

#2837 [FVM] Storage check optimisation
  engine/execution/computation/computer/computer_test.go
  engine/execution/state/bootstrap/bootstrap_test.go
  fvm/accounts_test.go
  fvm/contractFunctionInvocations.go
  fvm/contractFunctionInvoker.go
  fvm/executionParameters_test.go
  fvm/systemcontracts/system_contracts.go
  fvm/transactionInvoker_test.go
  fvm/transactionStorageLimiter.go
  fvm/transactionStorageLimiter_test.go
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
  module/trace/constants.go
  utils/unittest/execution_state.go
Labels: E&V Team

#2783 Observer integration tests
  apiproxy/access_api_proxy.go
  apiproxy/access_api_proxy_test.go
  cmd/observer/node_builder/observer_builder.go
  engine/access/rpc/engine_builder.go
  engine/access/rpc/forwarder.go
  integration/localnet/bootstrap.go
  integration/testnet/network.go
  integration/tests/access/access_test.go
  integration/tests/access/observer_test.go
Labels: S-Access
