Repository onflow/flow-go, pull requests merged in 2022-05, with the labels that each got.

#2357 Add weights for atree values
  fvm/meter/weighted/meter.go
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
Labels: Improvement

#2346 Permissionless contract updates
  fvm/fvm_test.go
  fvm/handler/accountKey_test.go
  fvm/handler/contract.go
  fvm/handler/contract_test.go
  fvm/mock/state/accounts.go
  fvm/state/accounts.go
Labels: Improvement

#2404 Add weights to newly introduced memory kinds
  engine/execution/computation/computer/computer_test.go
  fvm/meter/weighted/meter.go
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
Labels: Improvement

#2128 Bump codecov-action v1 to v2
  .github/workflows/ci.yml
Labels: Improvement

#2426 Cadence v0.23.3-patch.2
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
Labels: Improvement

#2451 Add missing weights for cadence memory kinds
  cmd/util/ledger/migrations/ordered_map_migration.go
  fvm/fvm_test.go
  fvm/meter/weighted/meter.go
  fvm/meter/weighted/meter_test.go
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
Labels: Improvement

#2477 Optimize Ledger.Get() by making Forest.Read() use ~5x fewer allocs/op and run ~20% faster
  cmd/util/cmd/read-execution-state/list-accounts/cmd.go
  ledger/complete/ledger.go
  ledger/complete/mtrie/forest.go
  ledger/complete/mtrie/forest_test.go
  ledger/complete/wal/checkpointer_test.go
  ledger/complete/wal/compactor_test.go
  ledger/trie.go
Labels: Performance

#2473 Optimize MTrie reading single path by adding Ledger.GetSingleValue() to boost speed and reduce memory use
  cmd/util/cmd/read-execution-state/list-accounts/cmd.go
  engine/execution/state/state.go
  ledger/complete/ledger.go
  ledger/complete/ledger_benchmark_test.go
  ledger/complete/ledger_test.go
  ledger/complete/mtrie/forest.go
  ledger/complete/mtrie/forest_test.go
  ledger/complete/mtrie/trie/trie.go
  ledger/complete/mtrie/trie/trie_test.go
  ledger/complete/wal/checkpointer_test.go
  ledger/complete/wal/compactor_test.go
  ledger/ledger.go
  ledger/mock/ledger.go
  ledger/partial/ledger.go
  ledger/partial/ledger_test.go
  ledger/partial/ptrie/partialTrie.go
  ledger/partial/ptrie/partialTrie_test.go
  ledger/trie.go
  module/chunks/chunkVerifier.go
Labels: enhancement, Performance

#2201 Remove comparison of key in MTrie payload.Equals() and add API comment about payload key
  ledger/common/encoding/encoding_test.go
  ledger/complete/mtrie/trie/trie.go
  ledger/ledger_test.go
  ledger/trie.go
  ledger/trie_test.go
Labels: Improvement

#2448 [Security] Remove unknown codeowners
  CODEOWNERS
Labels: Improvement

#2501 Update to Cadence v0.23.3-patch.3
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
Labels: Bugfix
