Repository onflow/flow-go, pull requests merged in 2022-04, with the labels that each got.

#2247 Update to Cadence v0.23.3
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
Labels: Bugfix

#2280 Drop checkpoint files from OS file cache to prevent file cache growing to hundreds of GB
  cmd/util/cmd/checkpoint-list-tries/cmd.go
  ledger/complete/ledger.go
  ledger/complete/wal/checkpointer.go
  ledger/complete/wal/checkpointer_test.go
  ledger/complete/wal/checkpointer_versioning_test.go
  ledger/complete/wal/syncrename.go
Labels: Improvement

#2281 Drop checkpoint files from OS file cache to prevent file cache growing to hundreds of GB
  cmd/util/cmd/checkpoint-list-tries/cmd.go
  ledger/complete/ledger.go
  ledger/complete/wal/checkpointer.go
  ledger/complete/wal/checkpointer_test.go
  ledger/complete/wal/checkpointer_versioning_test.go
  ledger/complete/wal/syncrename.go
Labels: Improvement, Performance

#2278 Memory weight assignment
  admin/tools.go
  cmd/util/cmd/epochs/cmd/reset_test.go
  cmd/util/ledger/migrations/ordered_map_migration.go
  cmd/util/ledger/reporters/fungible_token_tracker.go
  consensus/hotstuff/integration/slow_test.go
  consensus/integration/blockordelay_test.go
  consensus/integration/slow_test.go
  engine/execution/computation/execution_verification_test.go
  engine/execution/computation/programs_test.go
  engine/execution/state/bootstrap/bootstrap_test.go
  engine/execution/testutil/fixtures.go
  fvm/accounts_test.go
  fvm/blueprints/fees.go
  fvm/bootstrap.go
  fvm/context.go
  fvm/contractFunctionInvocations.go
  fvm/fvm.go
  fvm/fvm_bench_test.go
  fvm/fvm_test.go
  fvm/meter/weighted/meter.go
  fvm/meter/weighted/meter_test.go
  fvm/scriptEnv.go
  fvm/transactionEnv.go
  fvm/utils/cadenceValues.go
  go.mod
  go.sum
  integration/benchmark/tx_per_second_test.go
  integration/go.mod
  integration/go.sum
  integration/utils/scripts.go
  model/convert/service_event.go
  utils/unittest/execution_state.go
Labels: Improvement

#2336 Advise Linux to drop files from page cache (it was holding 425 GB of which 198+ GB were 3 checkpoint files)
  cmd/execution/main.go
  go.mod
  ledger/complete/wal/checkpointer.go
  ledger/complete/wal/checkpointer_test.go
  ledger/complete/wal/checkpointer_versioning_test.go
  ledger/complete/wal/fadvise.go
  ledger/complete/wal/fadvise_linux.go
  ledger/complete/wal/syncrename.go
  ledger/complete/wal/syncrename_test.go
Labels: Improvement, Performance
