Repository onflow/flow-go, pull requests merged in 2022-09, with the labels that each got.

#3117 [FVM] Cleanup fvm logging
  cmd/execution_builder.go
  cmd/util/ledger/reporters/account_reporter.go
  cmd/util/ledger/reporters/fungible_token_tracker_test.go
  cmd/verification_builder.go
  engine/execution/computation/computer/computer.go
  engine/execution/computation/computer/computer_test.go
  engine/execution/computation/execution_verification_test.go
  engine/execution/computation/manager_benchmark_test.go
  engine/execution/computation/manager_test.go
  engine/execution/computation/programs_test.go
  engine/execution/state/bootstrap/bootstrap.go
  engine/execution/testutil/fixtures.go
  engine/testutil/nodes.go
  engine/verification/utils/unittest/fixture.go
  fvm/accounts_test.go
  fvm/context.go
  fvm/contractFunctionInvocations.go
  fvm/contractFunctionInvoker.go
  fvm/contractFunctionInvoker_test.go
  fvm/fvm.go
  fvm/fvm_bench_test.go
  fvm/fvm_blockcontext_test.go
  fvm/fvm_test.go
  fvm/handler/programs_test.go
  fvm/reusable_cadence_runtime_test.go
  fvm/transactionInvoker.go
  fvm/transactionInvoker_test.go
  fvm/transaction_test.go
  integration/go.mod
  integration/go.sum
  module/chunks/chunkVerifier_test.go
  utils/debug/remoteDebugger.go
Labels: E&V Team

#3112 [FVM] Basic fuzzing and minor test change
  Makefile
  engine/execution/testutil/fixtures.go
  fvm/fvm_fuzz_test.go
  fvm/fvm_test.go
Labels: E&V Team

#3183 [FVM] Events in scripts do nothing instead of causing errors
  fvm/environment/event_emitter.go
  fvm/environment/event_emitter_test.go
Labels: Improvement, E&V Team

#3114 [FVM] Add interaction limit to FVM fuzzing
  fvm/fvm_fuzz_test.go
  fvm/state/state_holder.go
  fvm/transactionSequenceNum.go
  fvm/transactionVerifier.go
Labels: E&V Team

#3131 [FVM] Add expected event count to fuzzer
  fvm/fvm_fuzz_test.go
Labels: E&V Team

#3220 [FVM] Pass context by value
  fvm/bootstrap.go
  fvm/environment/mock/account_creator.go
  fvm/environment/mock/address_generator.go
  fvm/environment/mock/bootstrap_account_creator.go
  fvm/mock/transaction_processor.go
  fvm/transaction.go
  fvm/transactionInvoker.go
  fvm/transactionInvoker_test.go
  fvm/transactionSequenceNum.go
  fvm/transactionSequenceNum_test.go
  fvm/transactionVerifier.go
  fvm/transactionVerifier_test.go
  fvm/transaction_test.go
Labels: E&V Team

#3230 [FVM] Log err on TX failure
  fvm/transactionInvoker.go
Labels: E&V Team

#3235 [FVM] Refactor checkAccountsAreNotFrozen
  fvm/transactionVerifier.go
Labels: E&V Team

#3244 [FVM] Error Cleanup
  fvm/crypto/crypto_test.go
  fvm/errors/accounts.go
  fvm/errors/base.go
  fvm/errors/codes.go
  fvm/errors/contracts.go
  fvm/errors/errors.go
  fvm/errors/errors_test.go
  fvm/errors/execution.go
  fvm/errors/failures.go
  fvm/errors/txVerifier.go
  fvm/fvm_blockcontext_test.go
  fvm/fvm_test.go
  fvm/handler/accountKey_test.go
  fvm/meter/weighted_meter_test.go
  fvm/transactionVerifier_test.go
  fvm/transaction_test.go
Labels: E&V Team

#3121 Consensus Compliance Engine updated to conform to `Component` interface
  consensus/integration/epoch_test.go
  consensus/integration/integration_test.go
  consensus/integration/nodes_test.go
  consensus/integration/slow_test.go
  consensus/integration/stopper_test.go
  engine/collection/compliance/core.go
  engine/collection/compliance/engine.go
  engine/common/follower/engine.go
  engine/common/synchronization/engine.go
  engine/common/synchronization/engine_test.go
  engine/consensus/compliance.go
  engine/consensus/compliance/core.go
  engine/consensus/compliance/core_test.go
  engine/consensus/compliance/engine.go
  engine/consensus/compliance/engine_test.go
  engine/consensus/mock/proposal_provider.go
  engine/consensus/provider/engine.go
  engine/consensus/provider/engine_test.go
  engine/enqueue.go
  utils/unittest/irrecoverable.go
  utils/unittest/unittest.go
Labels: S-Consensus

#3271 Update to Cadence v0.27.0 and Go SDK v0.28.0
  access/validator.go
  fvm/meter/meter.go
  fvm/programs/block_programs.go
  fvm/programs/block_programs_test.go
  fvm/state/state_holder.go
  go.mod
  go.sum
  integration/go.mod
  integration/go.sum
Labels: Improvement

#3295 [FVM] Set ReusableCadenceRuntimePoolSize in bench tests
  fvm/fvm_bench_test.go
Labels: E&V Team
