Repository onflow/flow-go, pull requests merged in 2023-01, with the labels that each got.

#3733 Upgrade core contracts
  engine/execution/computation/execution_verification_test.go
  engine/execution/state/bootstrap/bootstrap_test.go
  fvm/fvm_test.go
  go.mod
  go.sum
  insecure/go.mod
  insecure/go.sum
  integration/go.mod
  integration/go.sum
  utils/unittest/execution_state.go
Labels: E&V Team

#3768 Ensure the same runtime config is used
  engine/execution/computation/computer/computer_test.go
  fvm/environment/system_contracts_test.go
  fvm/executionParameters_test.go
  fvm/runtime/reusable_cadence_runtime.go
Labels: Improvement

#3773 [v0.29-no-pacemaker] Update to cadence v0.31.1
  go.mod
  go.sum
  insecure/go.mod
  insecure/go.sum
  integration/go.mod
  integration/go.sum
Labels: Improvement

#3772 [v0.29] Update to cadence v0.31.1
  go.mod
  go.sum
  insecure/go.mod
  insecure/go.sum
  integration/go.mod
  integration/go.sum
Labels: Improvement

#3774 Update to cadence v0.31.1
  go.mod
  go.sum
  insecure/go.mod
  insecure/go.sum
  integration/go.mod
  integration/go.sum
Labels: Improvement

#3706 [FVM] Smart/partial programs cache invalidation
  fvm/derived/derived_block_data.go
  fvm/derived/derived_chain_data_test.go
  fvm/derived/invalidator.go
  fvm/environment/contract_updater.go
  fvm/environment/contract_updater_test.go
  fvm/environment/derived_data_invalidator.go
  fvm/environment/derived_data_invalidator_test.go
  fvm/environment/mock/derived_transaction_data.go
  fvm/environment/programs.go
  fvm/environment/programs_test.go
  fvm/programs/programs.go
Labels: E&V Team

#3808 [FVM]SetProgram can be called with nil
  fvm/environment/programs.go
  fvm/fvm_test.go
  go.mod
  go.sum
  insecure/go.mod
  insecure/go.sum
  integration/go.mod
  integration/go.sum
Labels: E&V Team

#3859 Start pacemaker before processing pending blocks
  consensus/hotstuff/eventhandler/event_handler.go
Labels: Bug

#3865 [FVM] Refactor accounts set storage used
  fvm/environment/accounts.go
Labels: E&V Team

#3871 [FVM] Add restriction that program loading cannot write to registers
  fvm/environment/programs.go
  fvm/state/state.go
Labels: E&V Team

#3870 [FVM] Split meter into components
  fvm/meter/computation_meter.go
  fvm/meter/event_meter.go
  fvm/meter/interaction_meter.go
  fvm/meter/memory_meter.go
  fvm/meter/meter.go
Labels: E&V Team
