Repository onflow/flow-go, pull requests merged in 2023-09, with the labels that each got.

#4644 Pass zerolog by value
  cmd/util/cmd/checkpoint-list-tries/cmd.go
  cmd/util/cmd/execution-state-extract/execution_state_extract.go
  cmd/util/ledger/migrations/account_based_migration.go
  fvm/environment/contract_updater.go
  fvm/environment/env.go
  fvm/environment/mock/environment.go
  fvm/environment/program_logger.go
  fvm/environment/system_contracts.go
  fvm/transactionInvoker.go
  ledger/complete/checkpoint_benchmark_test.go
  ledger/complete/compactor.go
  ledger/complete/wal/checkpoint_v5_test.go
  ledger/complete/wal/checkpoint_v6_leaf_reader.go
  ledger/complete/wal/checkpoint_v6_reader.go
  ledger/complete/wal/checkpoint_v6_test.go
  ledger/complete/wal/checkpoint_v6_writer.go
  ledger/complete/wal/checkpointer.go
  ledger/complete/wal/checkpointer_test.go
  ledger/complete/wal/checkpointer_versioning_test.go
  ledger/complete/wal/syncrename.go
  ledger/complete/wal/syncrename_test.go
  module/util/log.go
  module/util/log_test.go
Labels: E&V Team

#4679 Upgrade cadence and change to ReadRandom
  fvm/environment/facade_env.go
  fvm/environment/mock/environment.go
  fvm/environment/mock/random_generator.go
  fvm/environment/random_generator.go
  fvm/environment/random_generator_test.go
  go.mod
  go.sum
  insecure/go.mod
  insecure/go.sum
  integration/go.mod
  integration/go.sum
Labels: E&V Team

#4745 Flex: Improve models and comments
  fvm/flex/handler.go
  fvm/flex/models/models.go
Labels: Improvement

#4749 Flex: Get FlexAddress construction and return working
  fvm/flex/flex_test.go
  fvm/flex/stdlib/flex.cdc
  fvm/flex/stdlib/flex.gen.go
  fvm/flex/stdlib/flex.go
  go.mod
  go.sum
  insecure/go.mod
  insecure/go.sum
  integration/go.mod
  integration/go.sum
Labels: Improvement

#4729 [v0.31] Update to Cadence v0.39.15
  cmd/util/ledger/reporters/fungible_token_tracker.go
  go.mod
  go.sum
  insecure/go.mod
  insecure/go.sum
  integration/go.mod
  integration/go.sum
Labels: Bugfix
