Repository onflow/flow-go, pull requests merged in 2023-11, with the labels that each got.

#4844 [Crypto] improve shuffle test
  crypto/random/rand.go
  crypto/random/rand_test.go
  crypto/random/rand_utils.go
Labels: Improvement

#4990 Update cadence to v0.42.5
  go.mod
  go.sum
  insecure/go.mod
  insecure/go.sum
  integration/go.mod
  integration/go.sum
Labels: Improvement

#4989 [v0.32] Update cadence to v0.42.5
  go.mod
  go.sum
  insecure/go.mod
  insecure/go.sum
  integration/go.mod
  integration/go.sum
Labels: Improvement

#4773 [Networking] GossipSub-level Sybil Mitigation
  insecure/integration/functional/test/gossipsub/rpc_inspector/utils.go
  insecure/integration/functional/test/gossipsub/rpc_inspector/validation_inspector_test.go
  network/internal/p2pfixtures/fixtures.go
  network/p2p/consumers.go
  network/p2p/inspector/validation/control_message_validation_inspector.go
  network/p2p/inspector/validation/control_message_validation_inspector_test.go
  network/p2p/p2pbuilder/gossipsub/gossipSubBuilder.go
  network/p2p/p2pconf/gossipsub_rpc_inspectors.go
  network/p2p/p2plogging/internal/peerIdCache_test.go
  network/p2p/p2plogging/logging_test.go
  network/p2p/scoring/subscription_provider_test.go
  network/p2p/scoring/subscription_validator_test.go
  network/p2p/scoring/utils_test.go
  network/p2p/test/fixtures.go
  utils/unittest/fixtures.go
  utils/unittest/unittest.go
Labels: S-Network Layer, S-BFT

#4898 [Networking] Improves p2p node logging
  network/p2p/connection/connector.go
  network/p2p/p2pbuilder/libp2pNodeBuilder.go
  network/validator/target_validator.go
Labels: S-Network Layer

#4615 Add transaction ms per computation metrics
  model/flow/constants.go
  module/metrics/execution.go
Labels: Improvement, E&V Team

#5035 Fix epoch event docs
  state/protocol/events.go
Labels: Documentation
