Repository onflow/flow-go, pull requests merged in 2023-07, with the labels that each got.

#4544 Fix Version Beacon event conversion
  model/convert/service_event.go
  utils/unittest/service_events_fixtures.go
Labels: E&V Team

#4562 Fix missing events in block data uploaded to GCP
  engine/execution/ingestion/uploader/model.go
  engine/execution/ingestion/uploader/model_test.go
Labels: Bugfix, E&V Team

#4572 `scriptExecutor` should populate env values even when the script errors
  fvm/fvm_test.go
  fvm/script.go
Labels: Bug, Bugfix

#4546 Fix Version Beacon event conversion
  model/convert/service_event.go
  model/convert/service_event_test.go
  utils/unittest/service_events_fixtures.go
Labels: E&V Team

#4552 Git tag validation
  .github/workflows/ci.yml
  .github/workflows/semver-tags.yaml
  cmd/bootstrap/transit/cmd/utils.go
  cmd/build/version.go
  cmd/build/version_test.go
  cmd/execution_builder.go
  cmd/scaffold.go
  cmd/util/cmd/execution-state-extract/export_report.json
  engine/access/access_test.go
  engine/access/rest/routes/node_version_info_test.go
  engine/access/rpc/backend/backend.go
  engine/access/rpc/backend/backend_network.go
  engine/testutil/nodes.go
  integration/localnet/builder/bootstrap.go
Labels: E&V Team
