Repository onflow/flow-go, pull requests merged in 2023-10, with the labels that each got.

#4789 [Flex] Add and implement createFlowOwnedAccount
  fvm/flex/handler_test.go
  fvm/flex/models/account.go
  fvm/flex/models/handler.go
  fvm/flex/stdlib/emulator/flex.gen.go
  fvm/flex/stdlib/emulator/flex.go
  fvm/flex/stdlib/flex.cdc
  fvm/flex/stdlib/flex.go
  fvm/flex/stdlib/flex_test.go
Labels: Feature

#4794 [Flex] Implement Flex.Balance constructor and FlowOwnedAccount.call
  fvm/flex/models/tokenVault.go
  fvm/flex/stdlib/emulator/flex.gen.go
  fvm/flex/stdlib/emulator/flex.go
  fvm/flex/stdlib/flex.cdc
  fvm/flex/stdlib/flex.go
  fvm/flex/stdlib/flex_test.go
Labels: Feature

#4770 Remove required Chain flag from execution-state-extract
  cmd/util/cmd/execution-state-extract/cmd.go
Labels: E&V Team

#4720 [Networking] GossipSub Publish Message Validation (Unknown Topic Spam)
  config/default-config.yml
  insecure/integration/functional/test/gossipsub/rpc_inspector/validation_inspector_test.go
  integration/tests/bft/gossipsub/signature/requirement/orchestrator.go
  network/netconf/flags.go
  network/p2p/consumers.go
  network/p2p/distributor/gossipsub_inspector_test.go
  network/p2p/inspector/validation/control_message_validation_inspector.go
  network/p2p/inspector/validation/control_message_validation_inspector_test.go
  network/p2p/inspector/validation/errors.go
  network/p2p/inspector/validation/errors_test.go
  network/p2p/message/types.go
  network/p2p/mock/gossip_sub_inspector_suite.go
  network/p2p/mock/inspector_topic_oracle.go
  network/p2p/p2pbuilder/gossipsub/gossipSubBuilder.go
  network/p2p/p2pbuilder/inspector/suite.go
  network/p2p/p2pconf/gossipsub_rpc_inspectors.go
  network/p2p/p2plogging/internal/peerIdCache_test.go
  network/p2p/p2plogging/logging_test.go
  network/p2p/scoring/registry.go
  network/p2p/scoring/registry_test.go
  network/p2p/scoring/scoring_test.go
  network/p2p/test/fixtures.go
  network/p2p/unicast/cache/dialConfigCache_test.go
  network/p2p/unicast/cache/dialConfigEntity_test.go
  network/p2p/unicast/manager_test.go
  utils/unittest/fixtures.go
  utils/unittest/unittest.go
Labels: S-Network Layer, S-BFT

#4862 [Access] Get account bugfix with tests
  cmd/access/node_builder/access_node_builder.go
  integration/testnet/client.go
  integration/tests/access/access_api_test.go
  integration/utils/transactions.go
  module/execution/scripts.go
  module/execution/scripts_test.go
  module/state_synchronization/indexer/indexer_core.go
  module/state_synchronization/indexer/indexer_core_test.go
  storage/pebble/testutil.go
Labels: E&V Team

#4876 [FVM] EVM: Refactor stdlib to use new approach
  fvm/blueprints/contracts.go
  fvm/blueprints/scripts/deployContractTransactionTemplate.cdc
  fvm/bootstrap.go
  fvm/environment/account_creator.go
  fvm/evm/evm.go
  fvm/evm/evm_test.go
  fvm/evm/handler/handler.go
  fvm/evm/stdlib/contract.cdc
  fvm/evm/stdlib/contract.go
  fvm/evm/stdlib/contract_test.go
  fvm/evm/stdlib/emulator/flex.gen.go
  fvm/evm/stdlib/emulator/flex.go
  fvm/evm/stdlib/flex.cdc
  fvm/evm/stdlib/flex.go
  fvm/evm/stdlib/flex_test.go
  fvm/evm/testutils/accounts.go
  fvm/evm/testutils/cadence.go
  fvm/script.go
  fvm/transactionInvoker.go
Labels: Improvement
