Repository onflow/flow-go, pull requests merged in 2023-03, with the labels that each got.

#3972 Port programs cache changes and metrics
  engine/execution/computation/computer/computer.go
  engine/execution/computation/computer/computer_test.go
  fvm/derived/derived_block_data.go
  fvm/derived/derived_chain_data_test.go
  fvm/derived/invalidator.go
  fvm/environment/contract_updater.go
  fvm/environment/contract_updater_test.go
  fvm/environment/derived_data_invalidator.go
  fvm/environment/derived_data_invalidator_test.go
  fvm/environment/facade_env.go
  fvm/environment/mock/derived_transaction_data.go
  fvm/environment/mock/metrics_reporter.go
  fvm/environment/program_logger.go
  fvm/environment/programs.go
  fvm/environment/programs_test.go
  fvm/programs/programs.go
  module/metrics.go
  module/metrics/execution.go
  module/metrics/noop.go
  module/mock/execution_metrics.go
  module/mock/runtime_metrics.go
Labels: E&V Team

#3976 Refactor get or load program
  fvm/environment/meter.go
  fvm/environment/programs.go
  module/trace/constants.go
Labels: E&V Team

#3981 Commit nested transaction on derived value compute error
  fvm/derived/table.go
  fvm/derived/table_test.go
Labels: E&V Team

#3903 Epoch Height Boundary Index
  .golangci.yml
  consensus/hotstuff/signature/randombeacon_signer_store.go
  engine/collection/ingest/engine.go
  engine/execution/execution_test.go
  engine/verification/utils/unittest/fixture.go
  integration/tests/collection/ingress_test.go
  integration/tests/collection/suite.go
  model/flow/cluster.go
  model/flow/identifierList.go
  model/flow/identity.go
  state/cluster/root_block.go
  state/protocol/badger/mutator.go
  state/protocol/badger/mutator_test.go
  state/protocol/badger/snapshot.go
  state/protocol/badger/snapshot_test.go
  state/protocol/badger/state.go
  state/protocol/badger/state_test.go
  state/protocol/convert.go
  state/protocol/epoch.go
  state/protocol/errors.go
  state/protocol/inmem/cluster.go
  state/protocol/inmem/convert.go
  state/protocol/inmem/dkg.go
  state/protocol/inmem/encodable.go
  state/protocol/inmem/epoch.go
  state/protocol/inmem/params.go
  state/protocol/inmem/snapshot.go
  state/protocol/invalid/epoch.go
  state/protocol/mock/epoch.go
  state/protocol/util.go
  storage/badger/operation/heights.go
  storage/badger/operation/heights_test.go
  storage/badger/operation/prefix.go
  storage/errors.go
  utils/unittest/cluster.go
  utils/unittest/epoch_builder.go
Labels: Feature, S-Epochs

#3921 Start previous epoch cluster consensus components after epoch boundary
  engine/collection/epochmgr/engine.go
  engine/collection/epochmgr/engine_test.go
  model/cluster/payload.go
  module/builder/collection/builder.go
Labels: Bug, S-Epochs

#3950 Beacon Key Storage Error Docs / Handling Improvements
  consensus/hotstuff/signature/randombeacon_signer_store.go
  consensus/hotstuff/signature/randombeacon_signer_store_test.go
  consensus/hotstuff/verification/combined_signer_v2.go
  consensus/hotstuff/verification/combined_signer_v2_test.go
  consensus/hotstuff/verification/combined_signer_v3.go
  consensus/hotstuff/verification/combined_signer_v3_test.go
  module/signer.go
  storage/badger/dkg_state.go
  storage/badger/dkg_state_test.go
  storage/dkg.go
Labels: S-Consensus, Tech Debt

#4010 Remove account freezing
  engine/execution/computation/computer/computer_test.go
  engine/execution/state/bootstrap/bootstrap_test.go
  fvm/accounts_test.go
  fvm/bootstrap.go
  fvm/environment/account_freezer.go
  fvm/environment/account_key_updater.go
  fvm/environment/account_key_updater_test.go
  fvm/environment/accounts.go
  fvm/environment/accounts_status.go
  fvm/environment/accounts_status_test.go
  fvm/environment/contract_reader.go
  fvm/environment/contract_updater.go
  fvm/environment/contract_updater_test.go
  fvm/environment/derived_data_invalidator.go
  fvm/environment/derived_data_invalidator_test.go
  fvm/environment/env.go
  fvm/environment/facade_env.go
  fvm/environment/mock/account_freezer.go
  fvm/environment/mock/accounts.go
  fvm/environment/mock/contract_updater_stubs.go
  fvm/environment/mock/environment.go
  fvm/environment/programs.go
  fvm/environment/system_contracts.go
  fvm/errors/accounts.go
  fvm/errors/codes.go
  fvm/fvm_blockcontext_test.go
  fvm/runtime/reusable_cadence_runtime.go
  fvm/state/accounts_status.go
  fvm/state/accounts_status_test.go
  fvm/systemcontracts/system_contracts.go
  fvm/transactionInvoker.go
  fvm/transactionVerifier.go
  fvm/transactionVerifier_test.go
  fvm/transaction_test.go
  module/trace/constants.go
  utils/unittest/execution_state.go
Labels: E&V Team

#4002 Use GetOrCompute for programs
  fvm/derived/derived_block_data.go
  fvm/environment/programs.go
Labels: E&V Team

#4042 Update to Cadence v0.31.5-account-linking-improved-pragma
  fvm/fvm_test.go
  go.mod
  go.sum
  insecure/go.mod
  insecure/go.sum
  integration/go.mod
  integration/go.sum
  integration/tests/epochs/epoch_join_and_leave_an_test.go
Labels: Improvement

#4011 Remove unused/usafe Get/Set on Derived data
  engine/execution/computation/computer/computer_test.go
  fvm/derived/derived_block_data.go
  fvm/derived/derived_chain_data_test.go
  fvm/derived/table.go
  fvm/derived/table_test.go
  fvm/environment/meter.go
  fvm/environment/programs.go
  module/trace/constants.go
Labels: E&V Team

#3986 [Networking] Introducing Visibility to the GossipSub Scoring Mechanism
  cmd/access/node_builder/access_node_builder.go
  cmd/observer/node_builder/observer_builder.go
  cmd/scaffold.go
  follower/follower_builder.go
  insecure/corruptlibp2p/libp2p_node_factory.go
  insecure/corruptlibp2p/p2p_node.go
  insecure/corruptlibp2p/pubsub_adapter.go
  insecure/corruptlibp2p/pubsub_adapter_config.go
  insecure/internal/factory.go
  module/metrics.go
  module/metrics/gossipsub_score.go
  module/metrics/network.go
  module/metrics/noop.go
  module/mock/gossip_sub_metrics.go
  module/mock/gossip_sub_scoring_metrics.go
  module/mock/lib_p2_p_metrics.go
  module/mock/network_metrics.go
  network/internal/p2pfixtures/fixtures.go
  network/internal/testutils/testUtil.go
  network/p2p/builder.go
  network/p2p/cache.go
  network/p2p/libp2pNode.go
  network/p2p/mock/create_node_func.go
  network/p2p/mock/gossip_sub_adapter_config_func.go
  network/p2p/mock/gossip_sub_builder.go
  network/p2p/mock/gossip_sub_factory_func.go
  network/p2p/mock/lib_p2_p_factory_func.go
  network/p2p/mock/lib_p2_p_node.go
  network/p2p/mock/node_builder.go
  network/p2p/mock/peer_manager.go
  network/p2p/mock/peer_score.go
  network/p2p/mock/peer_score_exposer.go
  network/p2p/mock/peer_score_tracer.go
  network/p2p/mock/peer_scoring_builder.go
  network/p2p/mock/protocol_peer_cache.go
  network/p2p/mock/pub_sub_adapter.go
  network/p2p/mock/pub_sub_adapter_config.go
  network/p2p/p2pbuilder/gossipsub/gossipSubBuilder.go
  network/p2p/p2pbuilder/libp2pNodeBuilder.go
  network/p2p/p2pnode/gossipSubAdapter.go
  network/p2p/p2pnode/gossipSubAdapterConfig.go
  network/p2p/p2pnode/libp2pNode.go
  network/p2p/peerManager.go
  network/p2p/pubsub.go
  network/p2p/scoring/app_score_test.go
  network/p2p/scoring/score_option.go
  network/p2p/test/fixtures.go
  network/p2p/tracer/gossipSubScoreTracer.go
  network/p2p/tracer/gossipSubScoreTracer_test.go
Labels: S-Network Layer, S-BFT

#4049 [Exec] Adding collection result consumer type
  engine/execution/computation/computer/computer.go
  engine/execution/computation/computer/computer_test.go
  engine/execution/computation/computer/result_collector.go
  engine/execution/computation/execution_verification_test.go
  engine/execution/computation/manager.go
  engine/execution/computation/manager_benchmark_test.go
  engine/execution/computation/manager_test.go
  engine/execution/computation/programs_test.go
  engine/execution/computation/result/consumer.go
  engine/execution/messages.go
  engine/verification/utils/unittest/fixture.go
  fvm/fvm_bench_test.go
  fvm/state/view.go
  model/flow/ledger.go
  model/flow/transaction_result.go
  module/mempool/entity/executableblock.go
Labels: E&V Team

#4056 Change program dependencies to cadence location
  fvm/derived/dependencies.go
  fvm/derived/dependencies_test.go
  fvm/derived/derived_block_data.go
  fvm/environment/contract_updater.go
  fvm/environment/contract_updater_test.go
  fvm/environment/derived_data_invalidator.go
  fvm/environment/derived_data_invalidator_test.go
  fvm/environment/env.go
  fvm/environment/facade_env.go
  fvm/environment/mock/contract_updater.go
  fvm/environment/mock/environment.go
  fvm/environment/programs.go
  fvm/environment/programs_test.go
  fvm/transactionInvoker.go
Labels: E&V Team

#4060 Remove double counting of imports
  fvm/derived/derived_block_data.go
  fvm/environment/programs.go
  fvm/environment/programs_test.go
  fvm/errors/codes.go
  fvm/errors/execution.go
  fvm/fvm_test.go
Labels: E&V Team

#4092 Change panic to failure in programs
  fvm/environment/programs.go
Labels: E&V Team
