Repository onflow/flow-go, pull requests merged in 2023-05, with the labels that each got.

#4256 Add version beacon badger storage
  model/flow/version_beacon.go
  storage/badger/operation/common.go
  storage/badger/operation/common_test.go
  storage/badger/operation/prefix.go
  storage/badger/operation/version_beacon.go
  storage/badger/operation/version_beacon_test.go
  storage/badger/version_beacon.go
  storage/mock/version_beacons.go
  storage/version_beacon.go
  utils/unittest/fixtures.go
Labels: E&V Team

#4283 Add version beacon verify function
  go.mod
  model/flow/version_beacon.go
  model/flow/version_beacon_test.go
Labels: E&V Team

#4295 [ASLP] Adds cache module for reputation management system
  network/alsp/cache.go
  network/alsp/internal/cache.go
  network/alsp/internal/cache_entity.go
  network/alsp/internal/cache_test.go
  network/alsp/params.go
  network/alsp/record.go
Labels: S-Network Layer, S-BFT

#4312 [Fix] Fixes flaky `TestGossipSubSpamMitigationIntegration`
  insecure/rpc_inspector/validation_inspector_test.go
Labels: S-Network Layer

#4298 Change system transaction to have dual authorizers
  fvm/blueprints/scripts/systemChunkTransactionTemplateDualAuthorizer.cdc
  fvm/blueprints/system.go
Labels: E&V Team

#4285 Add version beacon to snapshot
  engine/execution/state/unittest/fixtures.go
  model/flow/version_beacon.go
  module/state_synchronization/requester/execution_data_requester_test.go
  state/protocol/badger/mutator.go
  state/protocol/badger/mutator_test.go
  state/protocol/badger/snapshot.go
  state/protocol/badger/state.go
  state/protocol/badger/state_test.go
  state/protocol/badger/validity.go
  state/protocol/badger/validity_test.go
  state/protocol/inmem/convert.go
  state/protocol/inmem/convert_test.go
  state/protocol/inmem/encodable.go
  state/protocol/inmem/snapshot.go
  state/protocol/invalid/snapshot.go
  state/protocol/mock/snapshot.go
  state/protocol/snapshot.go
  storage/badger/operation/version_beacon.go
  storage/badger/operation/version_beacon_test.go
  storage/badger/version_beacon.go
  storage/version_beacon.go
  utils/unittest/version_beacon.go
Labels: E&V Team

#4369 FVM bench test fix
  fvm/fvm_bench_test.go
Labels: E&V Team
