Repository onflow/flow-go, pull requests merged in 2023-12, with the labels that each got.

#5033 Unify core contracts address definitions
  cmd/collection/main.go
  cmd/consensus/main.go
  cmd/execution_builder.go
  cmd/util/cmd/common/transactions.go
  cmd/util/cmd/epochs/cmd/deploy.go
  cmd/util/ledger/reporters/account_reporter.go
  cmd/util/ledger/reporters/fungible_token_tracker.go
  cmd/util/ledger/reporters/fungible_token_tracker_test.go
  engine/execution/computation/computer/computer_test.go
  engine/execution/computation/execution_verification_test.go
  engine/execution/computation/manager_test.go
  engine/execution/testutil/fixtures_token.go
  fvm/blueprints/system.go
  fvm/bootstrap.go
  fvm/environment/account_creator.go
  fvm/environment/event_emitter.go
  fvm/environment/event_emitter_test.go
  fvm/environment/system_contracts.go
  fvm/evm/evm.go
  fvm/evm/evm_test.go
  fvm/evm/handler/handler_test.go
  fvm/fvm_bench_test.go
  fvm/fvm_blockcontext_test.go
  fvm/fvm_fuzz_test.go
  fvm/fvm_test.go
  fvm/script.go
  fvm/systemcontracts/system_contracts.go
  fvm/systemcontracts/system_contracts_test.go
  fvm/transactionInvoker.go
  insecure/go.mod
  insecure/go.sum
  insecure/integration/functional/test/gossipsub/scoring/ihave_spam_test.go
  integration/dkg/dkg_emulator_suite.go
  integration/epochs/epoch_qc_test.go
  integration/go.mod
  integration/go.sum
  integration/tests/mvp/common.go
  model/convert/fixtures_test.go
  model/convert/service_event.go
  model/convert/service_event_test.go
  model/flow/chain.go
  module/dkg/client.go
  module/epochs/base_client.go
  module/epochs/qc_client.go
  storage/badger/events_test.go
  utils/unittest/fvm.go
  utils/unittest/service_events_fixtures.go
Labels: E&V Team

#5092 [v0.32] Update cadence to v0.42.6
  go.mod
  go.sum
  insecure/go.mod
  insecure/go.sum
  integration/go.mod
  integration/go.sum
Labels: Improvement

#5093 Update cadence to v0.42.6
  go.mod
  go.sum
  insecure/go.mod
  insecure/go.sum
  integration/go.mod
  integration/go.sum
Labels: Improvement

#5070 Setup EVM account Flow vault during bootstrap
  fvm/blueprints/fees.go
  fvm/blueprints/scripts/setupStorageForAccount.cdc
  fvm/bootstrap.go
  fvm/fvm_bench_test.go
Labels: Flow EVM
