Repository onflow/flow-go, pull requests merged in 2023-04, with the labels that each got.

#4165 Cleanup stop control component
  engine/execution/ingestion/stop_control.go
Labels: E&V Team

#4209 Add version beacon service event model
  engine/access/access_test.go
  engine/common/rpc/convert/convert.go
  go.mod
  model/flow/service_event.go
  model/flow/service_event_test.go
  model/flow/version_beacon.go
  model/flow/version_beacon_test.go
  utils/unittest/fixtures.go
Labels: E&V Team

#4172 Separate integration test for version upgrades
  .github/workflows/ci.yml
  integration/Makefile
  integration/tests/upgrades/stop_at_height_test.go
  integration/tests/upgrades/suite.go
Labels: E&V Team

#4227 [FVM] Update flow-core-contracts to v0.12.2
  engine/execution/state/bootstrap/bootstrap_test.go
  go.mod
  go.sum
  insecure/go.mod
  insecure/go.sum
  integration/go.mod
  integration/go.sum
  integration/tests/epochs/suite.go
  integration/utils/templates/remove-node.cdc
  utils/unittest/execution_state.go
Labels: Improvement

#4226 Add version beacon contract
  engine/execution/computation/computer/computer_test.go
  engine/execution/state/bootstrap/bootstrap_test.go
  fvm/blueprints/scripts/deployNodeVersionBeaconTransactionTemplate.cdc
  fvm/blueprints/scripts/systemChunkTransactionTemplate.cdc
  fvm/blueprints/system.go
  fvm/blueprints/version_beacon.go
  fvm/bootstrap.go
  fvm/environment/event_emitter.go
  fvm/systemcontracts/system_contracts.go
  fvm/systemcontracts/system_contracts_test.go
  go.mod
  go.sum
  insecure/go.mod
  insecure/go.sum
  integration/go.mod
  integration/go.sum
  model/convert/service_event.go
  model/convert/service_event_test.go
  state/protocol/badger/mutator.go
  utils/unittest/execution_state.go
  utils/unittest/service_events_fixtures.go
Labels: E&V Team

#4260 Fix node verion beacon address
  fvm/systemcontracts/system_contracts.go
  fvm/systemcontracts/system_contracts_test.go
Labels: Bugfix, E&V Team

#4268 [ALSP] Implementation of Metrics Collection for Misbehavior Reporting in Reputation Management System (RMS)
  cmd/scaffold.go
  module/metrics.go
  module/metrics/alsp.go
  module/metrics/labels.go
  module/metrics/namespaces.go
  module/metrics/network.go
  module/metrics/noop.go
  module/mock/alsp_metrics.go
  module/mock/network_core_metrics.go
  module/mock/network_metrics.go
  network/alsp/manager.go
  network/alsp/manager_test.go
  network/p2p/conduit/conduit.go
  network/p2p/network.go
  network/stub/network.go
Labels: S-Network Layer, S-BFT

#4250 Add Version Beacon integration test
  integration/go.mod
  integration/tests/upgrades/suite.go
  integration/tests/upgrades/version_beacon_service_event_test.go
Labels: E&V Team
