Repository onflow/flow-go, pull requests merged in 2023-02, with the labels that each got.

#3888 Add cached programs metrics
  engine/execution/computation/computer/computer.go
  engine/execution/computation/computer/computer_test.go
  fvm/derived/derived_block_data.go
  fvm/environment/programs_test.go
  module/metrics.go
  module/metrics/execution.go
  module/metrics/noop.go
  module/mock/execution_metrics.go
Labels: E&V Team

#3896 Add programs chache hit/miss metrics
  fvm/environment/facade_env.go
  fvm/environment/mock/metrics_reporter.go
  fvm/environment/program_logger.go
  fvm/environment/programs.go
  module/metrics.go
  module/metrics/execution.go
  module/metrics/noop.go
  module/mock/execution_metrics.go
  module/mock/runtime_metrics.go
Labels: E&V Team

#3770 Upgrade core contracts - port to v0.29
  engine/execution/computation/execution_verification_test.go
  engine/execution/state/bootstrap/bootstrap_test.go
  fvm/fvm_test.go
  go.mod
  go.sum
  insecure/go.mod
  insecure/go.sum
  integration/go.mod
  integration/go.sum
  utils/unittest/execution_state.go
Labels: E&V Team

#3910 Enable account linking / AuthAccount capabilities on all networks except Mainnet
  engine/execution/computation/computer/computer_test.go
  engine/execution/computation/manager.go
  engine/execution/computation/manager_benchmark_test.go
  fvm/environment/env.go
  fvm/environment/runtime.go
  fvm/environment/system_contracts_test.go
  fvm/fvm_bench_test.go
  fvm/runtime/reusable_cadence_runtime.go
  fvm/runtime/reusable_cadence_runtime_test.go
Labels: Improvement

#3920 Enable Account Linking - Fix
  engine/execution/computation/computer/computer_test.go
  engine/execution/computation/manager.go
  engine/execution/computation/manager_benchmark_test.go
  fvm/environment/env.go
  fvm/environment/runtime.go
  fvm/environment/system_contracts_test.go
  fvm/executionParameters_test.go
  fvm/fvm_bench_test.go
  fvm/fvm_test.go
  fvm/runtime/reusable_cadence_runtime.go
  fvm/runtime/reusable_cadence_runtime_test.go
Labels: Bugfix, E&V Team

#3691 [Access] Add REST API metrics middleware
  engine/access/rest/middleware/metrics.go
  engine/access/rest/router.go
  go.mod
  go.sum
  insecure/go.mod
  insecure/go.sum
  integration/go.mod
  integration/go.sum
  module/metrics/noop.go
  module/metrics/rest_api.go
Labels: S-Access

#3899 [FVM] Debug log cadence logs
  fvm/environment/program_logger.go
Labels: E&V Team
