Repository onflow/flow-go, pull requests merged in 2023-06, with the labels that each got.

#4416 Account local ID generation
  engine/execution/state/bootstrap/bootstrap_test.go
  fvm/accounts_test.go
  fvm/environment/account_key_updater_test.go
  fvm/environment/account_local_id_generator.go
  fvm/environment/account_local_id_generator_test.go
  fvm/environment/accounts.go
  fvm/environment/accounts_status.go
  fvm/environment/accounts_status_test.go
  fvm/environment/accounts_test.go
  fvm/environment/facade_env.go
  fvm/environment/meter.go
  fvm/environment/mock/account_local_id_generator.go
  fvm/environment/mock/accounts.go
  module/trace/constants.go
  utils/unittest/execution_state.go
Labels: E&V Team

#4390 Update to Cadence v0.39.1
  cmd/util/ledger/reporters/account_reporter.go
  cmd/util/ledger/reporters/fungible_token_tracker.go
  engine/execution/computation/manager.go
  engine/execution/computation/manager_test.go
  fvm/blueprints/contracts.go
  fvm/blueprints/fees.go
  fvm/environment/mock/environment.go
  fvm/fvm_test.go
  fvm/meter/memory_meter.go
  fvm/runtime/wrapped_cadence_runtime.go
  go.mod
  go.sum
  insecure/go.mod
  insecure/go.sum
  integration/dkg/dkg_client_test.go
  integration/dkg/dkg_emulator_suite.go
  integration/epochs/cluster_epoch_test.go
  integration/epochs/epoch_qc_test.go
  integration/go.mod
  integration/go.sum
  integration/utils/emulator_client.go
Labels: Improvement

#4320 Add test for storage iteration with broken values
  fvm/fvm_test.go
Labels: Improvement

#4342 Stop Control with Version Beacons
  admin/commands/execution/stop_at_height.go
  admin/commands/execution/stop_at_height_test.go
  cmd/build/version.go
  cmd/build/version_test.go
  cmd/execution_builder.go
  engine/execution/ingestion/engine.go
  engine/execution/ingestion/engine_test.go
  engine/execution/ingestion/stop/stop_control.go
  engine/execution/ingestion/stop/stop_control_test.go
  engine/execution/ingestion/stop_control.go
  engine/execution/ingestion/stop_control_test.go
  engine/testutil/nodes.go
  integration/Makefile
  integration/tests/upgrades/stop_at_height_test.go
  integration/tests/upgrades/version_beacon_service_event_test.go
Labels: E&V Team

#4417 [Exec] Use CCF in self-describing mode to encode events (replaces JSON-CDC)
  engine/execution/computation/computer/computer_test.go
  engine/execution/computation/programs_test.go
  engine/execution/rpc/engine.go
  engine/execution/testutil/fixtures.go
  fvm/accounts_test.go
  fvm/environment/event_emitter_test.go
  fvm/environment/event_encoder.go
  fvm/fvm_bench_test.go
  fvm/fvm_blockcontext_test.go
  fvm/fvm_fuzz_test.go
  fvm/fvm_test.go
  integration/go.mod
  integration/go.sum
  model/convert/service_event.go
  utils/unittest/generator/events.go
  utils/unittest/service_events_fixtures.go
Labels: Feature, E&V Team

#4439 [v0.31] Update to Cadence v0.39.3
  go.mod
  go.sum
  insecure/go.mod
  insecure/go.sum
  integration/go.mod
  integration/go.sum
Labels: Improvement

#4444 Transaction logging fix
  cmd/execution_builder.go
Labels: E&V Team

#4445 port - Fix system transaction imports (#4443)
  fvm/systemcontracts/system_contracts.go
Labels: E&V Team

#4448 [0.31] Update to Cadence v0.39.5
  go.mod
  go.sum
  insecure/go.mod
  insecure/go.sum
  integration/go.mod
  integration/go.sum
Labels: Bugfix

#4446 port - Transaction logging fix
  cmd/execution_builder.go
Labels: E&V Team

#4474 Dependency tracking on load error
  fvm/environment/programs.go
  fvm/environment/programs_test.go
  fvm/fvm_test.go
Labels: E&V Team

#4475 port - Dependency tracking on load error #4474
  fvm/environment/programs.go
  fvm/environment/programs_test.go
  fvm/fvm_test.go
Labels: E&V Team

#4507 Update to Cadence v0.39.12
  go.mod
  go.sum
  insecure/go.mod
  insecure/go.sum
  integration/go.mod
  integration/go.sum
Labels: Improvement

#4508 [v0.31] Update to Cadence v0.39.12
  go.mod
  go.sum
  insecure/go.mod
  insecure/go.sum
  integration/go.mod
  integration/go.sum
Labels: Improvement

#4511 [Networking] Sets GossipSub RPC Inspector mandatory default
  cmd/access/node_builder/access_node_builder.go
  cmd/collection/main.go
  cmd/node_builder.go
  cmd/observer/node_builder/observer_builder.go
  cmd/scaffold.go
  config/base_flags.go
  config/config.go
  follower/follower_builder.go
  insecure/corruptlibp2p/libp2p_node_factory.go
  insecure/corruptlibp2p/pubsub_adapter.go
  insecure/rpc_inspector/validation_inspector_test.go
  network/internal/p2pfixtures/fixtures.go
  network/internal/testutils/testUtil.go
  network/message/gossipsub.go
  network/netconf/config.go
  network/netconf/connection_manager.go
  network/netconf/flags.go
  network/p2p/builder.go
  network/p2p/connection/connManager.go
  network/p2p/connection/connManager_test.go
  network/p2p/consumers.go
  network/p2p/distributor/gossipsub_inspector_test.go
  network/p2p/inspector/validation/control_message_validation_inspector.go
  network/p2p/inspector/validation/errors.go
  network/p2p/inspector/validation/errors_test.go
  network/p2p/inspector/validation/inspect_message_request.go
  network/p2p/libp2pNode.go
  network/p2p/message/types.go
  network/p2p/mock/collection_cluster_changes_consumer.go
  network/p2p/mock/gossip_sub_builder.go
  network/p2p/mock/gossip_sub_factory_func.go
  network/p2p/mock/gossip_sub_inspector_suite.go
  network/p2p/mock/gossip_sub_rpc_inspector_suite_factory_func.go
  network/p2p/mock/lib_p2_p_node.go
  network/p2p/mock/node_builder.go
  network/p2p/mock/pub_sub_adapter.go
  network/p2p/p2pbuilder/gossipsub/gossipSubBuilder.go
  network/p2p/p2pbuilder/inspector/aggregate.go
  network/p2p/p2pbuilder/inspector/rpc_inspector_builder.go
  network/p2p/p2pbuilder/inspector/suite.go
  network/p2p/p2pbuilder/libp2pNodeBuilder.go
  network/p2p/p2pconf/errors.go
  network/p2p/p2pconf/errors_test.go
  network/p2p/p2pconf/gossipsub.go
  network/p2p/p2pconf/gossipsub_rpc_inspectors.go
  network/p2p/p2pnode/gossipSubAdapter.go
  network/p2p/p2pnode/libp2pNode.go
  network/p2p/pubsub.go
  network/p2p/scoring/registry.go
  network/p2p/scoring/registry_test.go
  network/p2p/scoring/score_option.go
  network/p2p/scoring/scoring_test.go
  network/p2p/test/fixtures.go
Labels: S-Network Layer, S-BFT

#4492 [Routing Attacks] Mitigates invalid message delivery
  cmd/util/cmd/execution-state-extract/export_report.json
  insecure/cmd/mods_override.sh
  insecure/corruptlibp2p/gossipsub_spammer.go
  insecure/corruptlibp2p/pubsub_adapter.go
  insecure/corruptlibp2p/pubsub_adapter_config.go
  insecure/go.mod
  insecure/go.sum
  insecure/integration/functional/test/gossipsub/rpc_inspector/metrics_inspector_test.go
  insecure/integration/functional/test/gossipsub/rpc_inspector/utils.go
  insecure/integration/functional/test/gossipsub/rpc_inspector/validation_inspector_test.go
  insecure/integration/functional/test/gossipsub/scoring/scoring_test.go
  insecure/integration/tests/composability_test.go
  insecure/integration/tests/mock_orchestrator.go
  integration/go.mod
  integration/go.sum
  network/p2p/builder.go
  network/p2p/libp2pNode.go
  network/p2p/mock/gossip_sub_builder.go
  network/p2p/mock/lib_p2_p_node.go
  network/p2p/mock/peer_score.go
  network/p2p/mock/pub_sub_adapter.go
  network/p2p/mock/score_option_builder.go
  network/p2p/p2pbuilder/gossipsub/gossipSubBuilder.go
  network/p2p/p2pbuilder/libp2pNodeBuilder.go
  network/p2p/p2pnode/gossipSubAdapter.go
  network/p2p/p2pnode/gossipSubAdapterConfig.go
  network/p2p/p2pnode/libp2pNode.go
  network/p2p/pubsub.go
  network/p2p/scoring/README.md
  network/p2p/scoring/score_option.go
  network/p2p/test/message.go
  network/p2p/tracer/gossipSubScoreTracer_test.go
  network/p2p/utils/logger.go
  utils/unittest/bytes.go
  utils/unittest/strings.go
Labels: S-Network Layer, S-BFT
