Repository onflow/flow-go, pull requests merged in 2024-05, with the labels that each got.

#5847 Reuse static type cache across migrations in different accounts
  cmd/util/ledger/migrations/cadence.go
  cmd/util/ledger/migrations/cadence_values_migration.go
Labels: Performance

#5853 Do not return an error when block is unavailable due to expiry
  fvm/environment/block_info.go
  fvm/environment/block_info_test.go
  utils/unittest/fixtures.go
Labels: Bugfix

#5913 Optimize Cadence v0.42 + atree inlining migration
  cmd/util/ledger/migrations/atree_register_migration.go
  cmd/util/ledger/migrations/cadence_value_validation.go
  cmd/util/ledger/migrations/cadence_value_validation_test.go
  cmd/util/ledger/migrations/filter_unreferenced_slabs_migration.go
  cmd/util/ledger/migrations/fix_broken_data_migration.go
  cmd/util/ledger/migrations/utils.go
  go.mod
  go.sum
  insecure/go.mod
  insecure/go.sum
  integration/go.mod
  integration/go.sum
Labels: Performance

#5914 Optimize creation of new payloads
  cmd/util/cmd/execution-state-extract/execution_state_extract.go
  cmd/util/ledger/migrations/deploy_migration_test.go
  cmd/util/ledger/migrations/filter_unreferenced_slabs_migration_test.go
  cmd/util/ledger/migrations/fix_broken_data_migration_test.go
  cmd/util/ledger/util/registers/registers.go
Labels: Performance

#5916 Use faster atree funcs to speedup Cadence 1.0 migration
  cmd/util/ledger/migrations/account_storage_migration.go
  cmd/util/ledger/migrations/cadence_value_diff.go
  cmd/util/ledger/migrations/cadence_value_diff_test.go
  cmd/util/ledger/migrations/cadence_values_migration.go
  cmd/util/ledger/migrations/cadence_values_migration_test.go
  cmd/util/ledger/migrations/filter_unreferenced_slabs_migration.go
  cmd/util/ledger/migrations/filter_unreferenced_slabs_migration_test.go
  cmd/util/ledger/migrations/fix_broken_data_migration.go
  cmd/util/ledger/migrations/staged_contracts_migration_test.go
  cmd/util/ledger/migrations/utils.go
  cmd/util/ledger/util/registers/registers.go
  go.mod
  go.sum
  insecure/go.mod
  insecure/go.sum
  integration/go.mod
  integration/go.sum
Labels: Performance

#5929 Fix Cadence 1.0 migration error when address is used as register owner
  cmd/util/cmd/execution-state-extract/execution_state_extract.go
  cmd/util/ledger/util/payload_grouping.go
  cmd/util/ledger/util/payload_grouping_test.go
  ledger/common/convert/convert_test.go
  model/flow/ledger.go
Labels: Bugfix

#5901 Improve scheduling in account-based migration
  cmd/util/ledger/migrations/account_based_migration.go
  cmd/util/ledger/migrations/account_size_filter_migration.go
  cmd/util/ledger/util/registers/registers.go
  cmd/util/ledger/util/topn.go
  cmd/util/ledger/util/topn_test.go
Labels: Performance

#5948 Add Payload.Address() to allow migrations, etc. to reduce overhead
  cmd/util/ledger/util/payload_grouping.go
  ledger/common/convert/convert.go
  ledger/common/convert/convert_test.go
  ledger/trie.go
  ledger/trie_encoder.go
  ledger/trie_test.go
  module/state_synchronization/indexer/indexer_core_test.go
  storage/pebble/bootstrap_test.go
Labels: enhancement

#5211 receipt validator error handling
  engine/consensus/matching/core.go
  engine/consensus/matching/core_test.go
  model/flow/execution_result.go
  module/errors.go
  module/mock/receipt_validator.go
  module/receipt_validator.go
  module/validation/common.go
  module/validation/receipt_validator.go
  module/validation/receipt_validator_test.go
  state/protocol/badger/mutator.go
  state/protocol/badger/mutator_test.go
  state/protocol/chain_state.go
  state/protocol/invalid/snapshot.go
  state/protocol/snapshot.go
  storage/headers.go
  storage/index.go
  utils/logging/consts.go
  utils/unittest/chain_suite.go
  utils/unittest/fixtures.go
Labels: S-Consensus, Tech Debt, S-BFT
