Repository onflow/flow-go, pull requests merged in 2024-03, with the labels that each got.

#5488 Fix data race in account grouping for account based migration
  cmd/util/ledger/util/payload_grouping.go
  cmd/util/ledger/util/payload_grouping_test.go
Labels: Bugfix

#5499 Add migration diff util for testing and debugging migrations
  cmd/util/cmd/execution-state-extract/cmd.go
  cmd/util/cmd/execution-state-extract/execution_state_extract.go
  cmd/util/cmd/execution-state-extract/execution_state_extract_test.go
  cmd/util/ledger/migrations/cadence.go
  cmd/util/ledger/migrations/cadence_value_diff.go
  cmd/util/ledger/migrations/cadence_value_diff_test.go
  cmd/util/ledger/migrations/cadence_values_migration.go
  cmd/util/ledger/migrations/cadence_values_migration_test.go
Labels: Feature, Execution

#5525 Fix build typo
  cmd/Dockerfile
  insecure/Makefile
  integration/Makefile
  integration/benchmark/cmd/manual/Dockerfile
Labels: Bugfix

#5551 Fix import resolving during staged contract updates
  cmd/util/ledger/migrations/staged_contracts_migration.go
  cmd/util/ledger/migrations/staged_contracts_migration_test.go
  cmd/util/ledger/migrations/test-data/cadence_values_migration/test_contract_upgraded.cdc
Labels: Bugfix

#5565 Make contract update validation thread safe
  cmd/util/ledger/migrations/staged_contracts_migration.go
  cmd/util/ledger/migrations/staged_contracts_migration_test.go
Labels: Bugfix

#5594 Revert "Optimise merge registers for migrations"
  cmd/util/ledger/migrations/account_storage_migration.go
  cmd/util/ledger/migrations/atree_register_migration.go
  cmd/util/ledger/migrations/cadence_value_validation.go
  cmd/util/ledger/migrations/cadence_values_migration.go
  cmd/util/ledger/migrations/cadence_values_migration_test.go
  cmd/util/ledger/migrations/merge.go
  cmd/util/ledger/migrations/migrator_runtime.go
  cmd/util/ledger/migrations/transaction_migration.go
  cmd/util/ledger/util/payload_snapshot.go
  cmd/util/ledger/util/payload_snapshot_test.go
  cmd/util/ledger/util/util.go
Labels: Bugfix

#5591 [Cadence 1.0] Optionally check atree storage health before migration
  cmd/util/cmd/execution-state-extract/cmd.go
  cmd/util/cmd/execution-state-extract/execution_state_extract.go
  cmd/util/cmd/execution-state-extract/execution_state_extract_test.go
  cmd/util/ledger/migrations/cadence.go
  cmd/util/ledger/migrations/cadence_values_migration.go
  cmd/util/ledger/migrations/cadence_values_migration_test.go
  cmd/util/ledger/migrations/staged_contracts_migration_test.go
Labels: Improvement
