Repository onflow/flow-go, pull requests merged in 2024-04, with the labels that each got.

#5608 Add util command to extract payload by address
  cmd/util/cmd/root.go
Labels: Improvement

#5622 Fix storage health check in Cadence 1.0 migration
  cmd/util/ledger/migrations/cadence_values_migration.go
Labels: Bugfix

#5618 [Cadence 1.0] Fix and improve state migration
  cmd/util/cmd/execution-state-extract/cmd.go
  cmd/util/cmd/execution-state-extract/execution_state_extract.go
  cmd/util/cmd/execution-state-extract/execution_state_extract_test.go
  cmd/util/ledger/migrations/cadence.go
  cmd/util/ledger/migrations/cadence_values_migration.go
  cmd/util/ledger/migrations/cadence_values_migration_test.go
  cmd/util/ledger/migrations/change_contract_code_migration_test.go
  cmd/util/ledger/migrations/staged_contracts_migration.go
  cmd/util/ledger/migrations/staged_contracts_migration_test.go
Labels: Bugfix

#5636 Add storage health check flags for atree migration
  cmd/util/cmd/execution-state-extract/cmd.go
  cmd/util/cmd/execution-state-extract/execution_state_extract.go
  cmd/util/ledger/migrations/atree_register_migration.go
  cmd/util/ledger/migrations/atree_register_migration_test.go
  cmd/util/ledger/migrations/utils.go
Labels: Improvement

#5645 Add flag for verbose error output to migrations
  cmd/util/cmd/execution-state-extract/cmd.go
  cmd/util/ledger/migrations/cadence.go
  cmd/util/ledger/migrations/cadence_values_migration.go
  cmd/util/ledger/migrations/cadence_values_migration_test.go
Labels: Improvement

#5659 Collect staged contracts from the storage itself
  cmd/util/ledger/migrations/cadence.go
  cmd/util/ledger/migrations/change_contract_code_migration.go
  cmd/util/ledger/migrations/change_contract_code_migration_test.go
  cmd/util/ledger/migrations/staged_contracts_migration.go
  cmd/util/ledger/migrations/staged_contracts_migration_test.go
Labels: Improvement

#5668 Clean up EVM environment setup
  fvm/evm/evm.go
  fvm/evm/stdlib/contract.go
  fvm/evm/stdlib/contract_test.go
  fvm/script.go
  fvm/transactionInvoker.go
Labels: Improvement

#5737 Fix EVM load test
  integration/benchmark/load/load_type_test.go
Labels: Bugfix

#5736 Atree Inlining & Deduplication with Cadence v0.42
  cmd/util/ledger/migrations/atree_register_migration.go
  cmd/util/ledger/migrations/utils.go
  cmd/util/ledger/reporters/atree_decode_test.go
  cmd/util/ledger/util/util.go
  engine/execution/state/bootstrap/bootstrap_test.go
  fvm/accounts_test.go
  fvm/environment/account_key_updater_test.go
  fvm/environment/accounts.go
  fvm/environment/accounts_status.go
  fvm/environment/accounts_status_test.go
  fvm/environment/accounts_test.go
  fvm/environment/mock/accounts.go
  fvm/environment/mock/environment.go
  fvm/environment/mock/value_store.go
  fvm/environment/value_store.go
  fvm/evm/backends/wrappedEnv.go
  fvm/evm/emulator/state/collection.go
  fvm/evm/emulator/state/stateDB_test.go
  fvm/evm/testutils/backend.go
  fvm/evm/testutils/cadence.go
  go.mod
  go.sum
  insecure/go.mod
  insecure/go.sum
  integration/go.mod
  integration/go.sum
  model/flow/ledger_test.go
  utils/unittest/execution_state.go
Labels: enhancement

#5554 Atree Inlining & Deduplication with Cadence v1.0
  cmd/util/ledger/migrations/atree_register_migration.go
  cmd/util/ledger/migrations/cadence_value_diff.go
  cmd/util/ledger/migrations/cadence_values_migration.go
  cmd/util/ledger/migrations/utils.go
  cmd/util/ledger/util/migration_runtime_interface.go
  cmd/util/ledger/util/util.go
  engine/execution/state/bootstrap/bootstrap_test.go
  fvm/accounts_test.go
  fvm/environment/account_key_updater_test.go
  fvm/environment/accounts.go
  fvm/environment/accounts_status.go
  fvm/environment/accounts_status_test.go
  fvm/environment/accounts_test.go
  fvm/environment/mock/accounts.go
  fvm/environment/mock/environment.go
  fvm/environment/mock/value_store.go
  fvm/environment/value_store.go
  fvm/evm/backends/wrappedEnv.go
  fvm/evm/emulator/state/collection.go
  fvm/evm/emulator/state/stateDB_test.go
  fvm/evm/testutils/backend.go
  fvm/evm/testutils/cadence.go
  go.mod
  go.sum
  insecure/go.mod
  insecure/go.sum
  integration/go.mod
  integration/go.sum
  model/flow/ledger_test.go
  utils/unittest/execution_state.go
Labels: Execution

#5677 [EVM] Add bridging interface to EVM contract
  cmd/util/ledger/migrations/change_contract_code_migration.go
  fvm/bootstrap.go
  fvm/evm/stdlib/contract.cdc
  fvm/evm/stdlib/contract.go
  fvm/evm/stdlib/contract_test.go
  fvm/fvm_test.go
Labels: enhancement, Feature

#5756 Use existing storage health check
  cmd/util/ledger/migrations/cadence_values_migration.go
Labels: Improvement

#5758 Port #5653 to feature/atree-inlining-cadence-v0.42 branch
  cmd/util/cmd/execution-state-extract/cmd.go
  cmd/util/cmd/execution-state-extract/execution_state_extract.go
  cmd/util/ledger/migrations/filter_unreferenced_slabs_migration.go
  cmd/util/ledger/migrations/filter_unreferenced_slabs_migration_test.go
  cmd/util/ledger/util/util.go
  model/flow/ledger.go
Labels: Feature

#5653 Add a migration which detects and filters out unreferenced slabs
  cmd/util/cmd/execution-state-extract/cmd.go
  cmd/util/cmd/execution-state-extract/execution_state_extract.go
  cmd/util/ledger/migrations/cadence.go
  cmd/util/ledger/migrations/cadence_values_migration_test.go
  cmd/util/ledger/migrations/filter_unreferenced_slabs_migration.go
  cmd/util/ledger/migrations/filter_unreferenced_slabs_migration_test.go
  cmd/util/ledger/migrations/staged_contracts_migration_test.go
  cmd/util/ledger/util/util.go
  model/flow/ledger.go
Labels: Feature

#5765 Port #5755 to feature/atree-inlining-cadence-v0.42
  cmd/util/cmd/execution-state-extract/cmd.go
  cmd/util/cmd/execution-state-extract/execution_state_extract.go
  cmd/util/cmd/execution-state-extract/execution_state_extract_test.go
  cmd/util/ledger/migrations/account_based_migration.go
  cmd/util/ledger/migrations/fix_broken_data_migration.go
  cmd/util/ledger/migrations/fix_broken_data_migration_test.go
  cmd/util/ledger/migrations/utils.go
  cmd/util/ledger/util/util.go
Labels: Feature

#5755 Add migration to fix refs to non-existent registers
  cmd/util/cmd/execution-state-extract/cmd.go
  cmd/util/ledger/migrations/account_based_migration.go
  cmd/util/ledger/migrations/cadence.go
  cmd/util/ledger/migrations/fix_broken_data_migration.go
  cmd/util/ledger/migrations/fix_broken_data_migration_test.go
  cmd/util/ledger/migrations/utils.go
Labels: Feature

#5646 create snapshot map with multiple goroutines
  cmd/util/ledger/migrations/account_storage_migration.go
  cmd/util/ledger/migrations/atree_register_migration.go
  cmd/util/ledger/migrations/atree_register_migrator_runtime.go
  cmd/util/ledger/migrations/cadence.go
  cmd/util/ledger/migrations/cadence_value_diff_test.go
  cmd/util/ledger/migrations/cadence_value_validation.go
  cmd/util/ledger/migrations/cadence_value_validation_test.go
  cmd/util/ledger/migrations/cadence_values_migration.go
  cmd/util/ledger/migrations/cadence_values_migration_test.go
  cmd/util/ledger/migrations/contract_checking_migration.go
  cmd/util/ledger/migrations/filter_unreferenced_slabs_migration.go
  cmd/util/ledger/migrations/fix_broken_data_migration.go
  cmd/util/ledger/migrations/migrator_runtime.go
  cmd/util/ledger/migrations/prune_migration.go
  cmd/util/ledger/migrations/staged_contracts_migration.go
  cmd/util/ledger/migrations/staged_contracts_migration_test.go
  cmd/util/ledger/migrations/transaction_migration.go
  cmd/util/ledger/util/snapshot/errors.go
  cmd/util/ledger/util/snapshot/payload_snapshot.go
  cmd/util/ledger/util/snapshot/payload_snapshot_test.go
Labels: Improvement

#5759 Unskip migration of Testnet accounts with broken data
  cmd/util/ledger/migrations/account_based_migration.go
Labels: Improvement

#5803 Improve migration logging, reports, and new file for very old problematic slabs
  cmd/util/ledger/migrations/cadence.go
  cmd/util/ledger/migrations/filter_unreferenced_slabs_migration.go
  cmd/util/ledger/migrations/filter_unreferenced_slabs_migration_test.go
  cmd/util/ledger/migrations/fix_broken_data_migration.go
  cmd/util/ledger/migrations/fix_broken_data_migration_test.go
Labels: Improvement

#5805 Port PR #5803 to Improve migration logging, reports, and output file
  cmd/util/cmd/execution-state-extract/execution_state_extract.go
  cmd/util/ledger/migrations/filter_unreferenced_slabs_migration.go
  cmd/util/ledger/migrations/filter_unreferenced_slabs_migration_test.go
  cmd/util/ledger/migrations/fix_broken_data_migration.go
  cmd/util/ledger/migrations/fix_broken_data_migration_test.go
Labels: Improvement
