Repository onflow/flow-go, pull requests merged in 2024-08, with the labels that each got.

#6225 [Util] Add support for detecting differing accounts
  cmd/util/cmd/diff-states/cmd.go
  cmd/util/cmd/diff-states/diff_states_test.go
  go.mod
Labels: Improvement

#6303 Set capability issue handler in capability value migration
  cmd/util/ledger/migrations/cadence_values_migration.go
  cmd/util/ledger/migrations/cadence_values_migration_test.go
Labels: Bugfix

#6312 Report and skip storage caps with no borrow type
  cmd/util/ledger/migrations/cadence.go
  cmd/util/ledger/migrations/cadence_values_migration.go
  cmd/util/ledger/migrations/cadence_values_migration_test.go
  go.mod
  go.sum
  insecure/go.mod
  insecure/go.sum
  integration/go.mod
  integration/go.sum
Labels: Bugfix

#6322 Improve storage capability migration
  cmd/util/ledger/migrations/cadence.go
  cmd/util/ledger/migrations/cadence_values_migration.go
  cmd/util/ledger/migrations/cadence_values_migration_test.go
  go.mod
  go.sum
  insecure/go.mod
  insecure/go.sum
  integration/go.mod
  integration/go.sum
Labels: Improvement

#6363 Move and export some migration funcs to util package for reuse
  cmd/util/cmd/execution-state-extract/execution_state_extract.go
  cmd/util/ledger/migrations/cadence_value_diff.go
  cmd/util/ledger/migrations/cadence_values_migration.go
  cmd/util/ledger/migrations/filter_unreferenced_slabs_migration.go
  cmd/util/ledger/migrations/fix_broken_data_migration.go
  cmd/util/ledger/migrations/utils.go
  cmd/util/ledger/util/atree_util.go
  cmd/util/ledger/util/registers_util.go
Labels: Improvement

#6364 Add check-storage command to util program to check storage health of execution state
  cmd/util/cmd/check-storage/cmd.go
  cmd/util/cmd/root.go
  cmd/util/ledger/util/registers/registers.go
Labels: enhancement

#6341 Allow using interface-converted type-requirement in fields
  cmd/util/ledger/migrations/cadence.go
  cmd/util/ledger/migrations/cadence_values_migration_test.go
  cmd/util/ledger/migrations/change_contract_code_migration.go
  cmd/util/ledger/migrations/change_contract_code_migration_test.go
  cmd/util/ledger/migrations/contract_checking_migration.go
  cmd/util/ledger/migrations/staged_contracts_migration.go
  cmd/util/ledger/migrations/staged_contracts_migration_test.go
  cmd/util/ledger/migrations/static_type_migration.go
  cmd/util/ledger/migrations/type_requirements_extractor.go
Labels: Improvement

#6399 Skip EVM storage account in `check-storage` command
  cmd/util/cmd/check-storage/cmd.go
Labels: Bugfix

#6394 [FVM] Recover NFT Collections
  cmd/util/ledger/migrations/contract_checking_migration_test.go
  fvm/environment/program_recovery.go
Labels: Feature

#6406 Add support for `cap_tag` domain in `check-storage` command of `util` program
  cmd/util/cmd/check-storage/cmd.go
  cmd/util/ledger/util/util.go
Labels: Bugfix

#6407 Add support for `cap_tag` domain in `diff-states`
  cmd/util/cmd/diff-states/cmd.go
Labels: Bugfix

#6416 Port PR #6401 (Skip EVM storage account for value comparison in diff-states cmd) to v0.37 branch
  cmd/util/cmd/diff-states/cmd.go
Labels: Bugfix

#6417 Port PR #6406 (Add support for `cap_tag` domain in check-storage cmd) to v0.37 branch
  cmd/util/cmd/check-storage/cmd.go
  cmd/util/ledger/util/util.go
Labels: Bugfix

#6418 Port PR #6407 (Add support for `cap_tag` domain in `diff-states` cmd) to v0.37 branch
  cmd/util/cmd/diff-states/cmd.go
Labels: Bugfix
