Repository onflow/flow-go, pull requests merged in 2024-07, with the labels that each got.

#6176 Add support for JSONL report format as alternative to JSON array report
  cmd/util/cmd/diff-states/cmd.go
  cmd/util/cmd/diff-states/diff_states_test.go
  cmd/util/ledger/reporters/reporter_output.go
  cmd/util/ledger/reporters/reporter_output_test.go
Labels: Improvement

#6193 Optimize migrations by creating output payloads file in parallel to new trie creation
  cmd/util/cmd/execution-state-extract/cmd.go
  cmd/util/cmd/execution-state-extract/execution_state_extract.go
  cmd/util/cmd/execution-state-extract/execution_state_extract_test.go
  cmd/util/ledger/util/payload_file.go
Labels: Performance

#6200 Port PR 6193 to master (speedup migration by ~21 minutes on m1-ultramem-160)
  cmd/util/cmd/execution-state-extract/cmd.go
  cmd/util/cmd/execution-state-extract/execution_state_extract.go
  cmd/util/cmd/execution-state-extract/execution_state_extract_test.go
Labels: Performance

#6190 [Flow EVM] Avoid hex encoding/decoding for event fields of type bytes
  engine/execution/state/bootstrap/bootstrap_test.go
  fvm/evm/evm_test.go
  fvm/evm/handler/handler_test.go
  fvm/evm/stdlib/contract.cdc
  fvm/evm/types/events.go
  fvm/evm/types/events_test.go
  fvm/evm/types/utils.go
  fvm/evm/types/utils_test.go
  utils/unittest/execution_state.go
Labels: Flow EVM

#6195 [Flow EVM] Pre-work for delaying the EVM block formation
  engine/execution/state/bootstrap/bootstrap_test.go
  fvm/evm/emulator/config.go
  fvm/evm/evm_test.go
  fvm/evm/handler/blockstore.go
  fvm/evm/handler/blockstore_benchmark_test.go
  fvm/evm/handler/blockstore_test.go
  fvm/evm/handler/handler.go
  fvm/evm/stdlib/contract.cdc
  fvm/evm/stdlib/contract.go
  fvm/evm/stdlib/contract_test.go
  fvm/evm/testutils/misc.go
  fvm/evm/types/block.go
  fvm/evm/types/block_test.go
  fvm/evm/types/events.go
  fvm/evm/types/events_test.go
  fvm/evm/types/handler.go
  fvm/evm/types/result.go
  fvm/evm/types/result_test.go
  utils/unittest/execution_state.go
Labels: Flow EVM

#6231 [Util] Add command to run a script
  cmd/util/cmd/root.go
  cmd/util/cmd/run-script/cmd.go
Labels: Feature

#6224 [Flow EVM] Improve event emission
  fvm/evm/events/events.go
  fvm/evm/events/events_test.go
  fvm/evm/events/utils.go
  fvm/evm/events/utils_test.go
  fvm/evm/evm_test.go
  fvm/evm/handler/handler.go
  fvm/evm/handler/handler_test.go
  fvm/evm/stdlib/checking.go
  fvm/evm/stdlib/type.go
  fvm/evm/stdlib/type_test.go
  fvm/evm/testutils/event.go
  fvm/evm/types/utils.go
  fvm/evm/types/utils_test.go
  fvm/fvm_test.go
  fvm/systemcontracts/system_contracts.go
Labels: Bugfix, Improvement

#6226 [Flow EVM] Extending block hash lookup range to the last 256 with minimum storage overhead
  fvm/evm/handler/blockHashList.go
  fvm/evm/handler/blockHashList_test.go
  fvm/evm/handler/blockstore.go
  fvm/evm/handler/blockstore_test.go
  fvm/evm/types/blockHashList.go
Labels: Flow EVM

#6232 [Flow EVM] Refactoring precompiled contract call tracker
  fvm/evm/emulator/config.go
  fvm/evm/emulator/emulator.go
  fvm/evm/emulator/emulator_test.go
  fvm/evm/emulator/tracker.go
  fvm/evm/emulator/tracker_test.go
  fvm/evm/precompiles/precompile.go
  fvm/evm/precompiles/precompile_test.go
  fvm/evm/precompiles/replayer.go
  fvm/evm/precompiles/replayer_test.go
  fvm/evm/testutils/misc.go
  fvm/evm/types/emulator.go
  fvm/evm/types/precompiled.go
  fvm/evm/types/precompiled_test.go
Labels: Flow EVM
