Repository onflow/flow-go, pull requests merged in 2024-02, with the labels that each got.

#5389 Add utility to extract payloads by addresses
  cmd/util/cmd/extract-payloads-by-address/cmd.go
  cmd/util/cmd/extract-payloads-by-address/extract_payloads_test.go
Labels: enhancement, Performance, E&V Team

#5384 [Flow EVM] Add tests to assert that Flow EVM events can be properly CCF encoded/decoded
  fvm/evm/types/events_test.go
Labels: Flow EVM

#5386 Optimize migration by adding ability to read or extract payloads from state
  cmd/util/cmd/execution-state-extract/cmd.go
  cmd/util/cmd/execution-state-extract/execution_state_extract.go
  cmd/util/cmd/execution-state-extract/execution_state_extract_test.go
  cmd/util/cmd/extract-payloads-by-address/cmd.go
  cmd/util/cmd/extract-payloads-by-address/extract_payloads_test.go
  cmd/util/ledger/util/payload_file.go
  cmd/util/ledger/util/payload_file_test.go
Labels: enhancement, Performance, E&V Team, spork improvements

#5405 Unify system-contracts migration and staged-contracts migration
  cmd/util/ledger/migrations/cadence.go
  cmd/util/ledger/migrations/cadence_values_migration_test.go
  cmd/util/ledger/migrations/change_contract_code_migration.go
  cmd/util/ledger/migrations/change_contract_code_migration_test.go
  cmd/util/ledger/migrations/migrator_runtime.go
  cmd/util/ledger/migrations/staged_contracts_migration.go
  cmd/util/ledger/migrations/staged_contracts_migration_test.go
  cmd/util/ledger/util/migration_runtime_interface.go
Labels: Improvement

#5438 Add version, partial state indicator, and checksum to payload file (intermediate migration file)
  cmd/util/cmd/execution-state-extract/cmd.go
  cmd/util/cmd/execution-state-extract/execution_state_extract.go
  cmd/util/cmd/execution-state-extract/execution_state_extract_test.go
  cmd/util/cmd/extract-payloads-by-address/cmd.go
  cmd/util/cmd/extract-payloads-by-address/extract_payloads_test.go
  cmd/util/ledger/util/payload_file.go
  cmd/util/ledger/util/payload_file_test.go
  cmd/util/ledger/util/payload_grouping.go
  ledger/complete/wal/checkpointer.go
Labels: Improvement, E&V Team
