Repository onflow/flow-go, pull requests merged in 2024-09, with the labels that each got.

#6430 Add support for checking EVM registers in `check-storage` command
  cmd/util/cmd/check-storage/cmd.go
  cmd/util/cmd/check-storage/evm_account_storage_health.go
  cmd/util/cmd/check-storage/evm_account_storage_health_test.go
Labels: Improvement

#6377 [FVM] Fix metering invalidation
  fvm/environment/derived_data_invalidator.go
  fvm/environment/derived_data_invalidator_test.go
  fvm/environment/value_store.go
  fvm/executionParameters.go
  fvm/script.go
  fvm/storage/derived/derived_block_data.go
  fvm/storage/derived/table.go
  fvm/transactionInvoker.go
Labels: Performance

#6453 update to transit script pull command to download file if md5 of remote file is not known
  cmd/bootstrap/transit/cmd/pull.go
Labels: Bug

#6478 Update `checkpoint-collect-stats` command to support payloads file and state commitment
  cmd/util/cmd/checkpoint-collect-stats/cmd.go
  ledger/complete/ledger_stats.go
Labels: Improvement

#6482 Collect and report more stats in `checkpoint-collect-stats` command
  cmd/util/cmd/checkpoint-collect-stats/cmd.go
Labels: enhancement
