Repository onflow/flow-go, pull requests merged in 2025-02, with the labels that each got.

#6882 Add stats about account format versions to util's `checkpoint-collect-stats` command
  cmd/util/cmd/checkpoint-collect-stats/account_stats.go
  cmd/util/cmd/checkpoint-collect-stats/cmd.go
  cmd/util/cmd/checkpoint-collect-stats/stats_utils.go
  go.mod
  go.sum
Labels: Improvement

#6860 [Flow EVM] Trigger `OnLog` tracer hooks upon successful call & tx results
  fvm/evm/emulator/emulator.go
Labels: Tech Debt, Flow EVM

#6987 Remove last remnants of Cadence 1.0 and authorization fixes migrations
  cmd/util/cmd/execution-state-extract/cmd.go
Labels: Tech Debt

#6977 Add support for account format v2 in util `check-storage`
  cmd/util/cmd/check-storage/cmd.go
  cmd/util/cmd/check-storage/evm_account_storage_health.go
  cmd/util/cmd/checkpoint-collect-stats/account_stats.go
  cmd/util/cmd/diff-states/cmd.go
  cmd/util/ledger/migrations/cadence_value_diff.go
Labels: Improvement

#6993 Add `--exclude-randombeaconhistory` to `diff-states` cmd in `util` program
  cmd/util/cmd/diff-states/cmd.go
  cmd/util/ledger/migrations/cadence_value_diff.go
  cmd/util/ledger/migrations/cadence_value_diff_test.go
Labels: Improvement

#7050 Update EVM `ViewProvider` to return block `View` at its end state
  fvm/evm/offchain/query/viewProvider.go
Labels: Flow EVM

#7016 Refactor `util` program `diff-states` cmd
  cmd/util/cmd/diff-states/cmd.go
  cmd/util/ledger/migrations/cadence_value_diff.go
Labels: Improvement
