Repository onflow/flow-go, pull requests merged in 2025-05, with the labels that each got.

#7373 Reduce state extraction w/o migration by ~29 minutes (~2.5x speedup)
  cmd/util/cmd/atree_inlined_status/cmd.go
  cmd/util/cmd/check-storage/cmd.go
  cmd/util/cmd/diff-states/cmd.go
  cmd/util/cmd/execution-state-extract/cmd.go
  cmd/util/cmd/execution-state-extract/execution_state_extract.go
  cmd/util/cmd/export-evm-state/cmd.go
  cmd/util/cmd/generate-authorization-fixes/cmd.go
  cmd/util/cmd/run-script/cmd.go
  cmd/util/ledger/util/state.go
Labels: Performance

#7328 Update to and enable EVM Pectra hard-fork
  fvm/evm/emulator/config.go
  fvm/evm/emulator/emulator.go
  fvm/evm/emulator/state/delta.go
  fvm/evm/emulator/state/delta_test.go
  fvm/evm/emulator/state/stateDB.go
  fvm/evm/emulator/state/stateDB_test.go
  fvm/evm/evm_test.go
  fvm/evm/types/call.go
  fvm/evm/types/result.go
  fvm/evm/types/state.go
  go.mod
  go.sum
  insecure/go.mod
  insecure/go.sum
  integration/go.mod
  integration/go.sum
Labels: Flow EVM

#7339 [Access] Update websockets events and account status reponses to use json-cdc encoding
  engine/access/rest/websockets/data_providers/account_statuses_provider.go
  engine/access/rest/websockets/data_providers/account_statuses_provider_test.go
  engine/access/rest/websockets/data_providers/events_provider.go
  engine/access/rest/websockets/data_providers/events_provider_test.go
Labels: Bug, S-Access

#7400 [Storage] Fix Writer.Set() & Writer.Delete() args not being safe to modify (BadgerDB)
  storage/operation/badgerimpl/writer.go
  storage/operation/badgerimpl/writer_test.go
  storage/operation/writes_test.go
Labels: Bugfix

#7399 Fix multiple versions of msgpack being used
  engine/common/provider/engine.go
  engine/common/provider/engine_test.go
  engine/common/requester/engine.go
  engine/common/requester/engine_test.go
  engine/execution/execution_test.go
  go.mod
  go.sum
  insecure/go.mod
  insecure/go.sum
  integration/go.mod
  integration/go.sum
  model/encodable/keys.go
  model/flow/identity.go
  model/flow/service_event_test.go
  storage/operation/iterate_bench_test.go
  storage/operation/reads.go
  storage/operation/writes.go
Labels: Improvement

#7426 [Execution] Fix event index for service events
  fvm/environment/event_emitter.go
  utils/unittest/fvm.go
Labels: Breaking Change
