Repository onflow/flow-go, pull requests merged in 2025-04, with the labels that each got.

#7229 [Storage] Close BadgerDB before db init functions return error
  storage/badger/init.go
Labels: Bugfix

#7230 [Storage] Remove old code in `initBadgerDB()`
  cmd/scaffold.go
Labels: Improvement

#7238 [Storage] Optimize storing execution receipts in BadgerDB
  storage/badger/receipts.go
Labels: Improvement

#7156 Bump `onflow/go-ethereum` dependency to `v1.14.8`
  go.mod
  go.sum
  insecure/go.mod
  insecure/go.sum
  integration/go.mod
  integration/go.sum
Labels: Flow EVM

#7243 [Storage] Optimize speed & memory for generating db keys (BadgerDB and Pebble)
  storage/badger/operation/common.go
  storage/badger/operation/common_test.go
  storage/badger/operation/prefix.go
  storage/operation/prefix.go
  storage/operation/prefix_bench_test.go
  storage/operation/prefix_test.go
  storage/pebble/operation/prefix.go
Labels: Performance

#7254 [Storage] Discard BadgerDB transaction when iterator is closed
  storage/operation/badgerimpl/iterator.go
Labels: Bugfix

#7257 [Storage] Add `Closer` to Batch interface and use it to prevent memory leak (BadgerDB & Pebble)
  cmd/util/cmd/rollback-executed-height/cmd/rollback_executed_height.go
  cmd/util/cmd/rollback-executed-height/cmd/rollback_executed_height_test.go
  module/block_iterator/executor/executor.go
  module/state_synchronization/indexer/indexer_core.go
  storage/mock/batch.go
  storage/operation/badgerimpl/writer.go
  storage/operation/pebbleimpl/writer.go
  storage/operations.go
  storage/store/transaction_results_test.go
Labels: Bugfix

#7241 Bump `onflow/go-ethereum` dependency to `v1.15.9`
  fvm/evm/emulator/config.go
  fvm/evm/emulator/emulator.go
  fvm/evm/emulator/state/delta.go
  fvm/evm/emulator/state/delta_test.go
  fvm/evm/emulator/state/stateDB.go
  fvm/evm/emulator/state/stateDB_test.go
  fvm/evm/evm_test.go
  fvm/evm/handler/handler.go
  fvm/evm/offchain/blocks/block_context.go
  fvm/evm/types/call.go
  fvm/evm/types/emulator.go
  fvm/evm/types/result.go
  fvm/evm/types/state.go
  go.mod
  go.sum
  insecure/go.mod
  insecure/go.sum
  integration/go.mod
  integration/go.sum
Labels: Flow EVM

#7323 [Storage] Fix batch remove in ServiceEvents to use the correct batch (BadgerDB, Pebble)
  storage/store/events.go
Labels: Bugfix

#7321 [Access] Add support for multi-store reading of collections & transactions in Access Nodes
  cmd/access/node_builder/access_node_builder.go
  cmd/execution_builder.go
  cmd/node_builder.go
  cmd/scaffold.go
  cmd/util/cmd/exec-data-json-export/delta_snapshot_exporter.go
  cmd/util/cmd/read-badger/cmd/stats.go
  cmd/verification_builder.go
  engine/execution/migration/badgerpebble.go
  engine/execution/state/bootstrap/bootstrap.go
  engine/execution/state/state.go
  module/block_iterator/executor/executor_test.go
  module/block_iterator/latest/sealed_and_executed.go
  storage/mock/db.go
  storage/operation/badgerimpl/dbstore.go
  storage/operation/chunk_data_packs_test.go
  storage/operation/collections_test.go
  storage/operation/commits_test.go
  storage/operation/computation_result_test.go
  storage/operation/events_test.go
  storage/operation/interactions_test.go
  storage/operation/multi_dbstore.go
  storage/operation/multi_iterator_test.go
  storage/operation/multi_reader_test.go
  storage/operation/multi_seeker_test.go
  storage/operation/pebbleimpl/dbstore.go
  storage/operation/receipts_test.go
  storage/operation/results_test.go
  storage/operation/stats_test.go
  storage/operation/transactions_test.go
  storage/operation/version_beacon_test.go
  storage/operations.go
  storage/store/approvals.go
  storage/store/cache_test.go
  storage/store/chunk_data_packs.go
  storage/store/chunks_queue.go
  storage/store/chunks_queue_test.go
  storage/store/collections.go
  storage/store/commits.go
  storage/store/computation_result.go
  storage/store/consumer_progress.go
  storage/store/events.go
  storage/store/light_transaction_results.go
  storage/store/my_receipts.go
  storage/store/receipts.go
  storage/store/results.go
  storage/store/transaction_result_error_messages.go
  storage/store/transaction_results.go
  storage/store/transactions.go
  storage/store/version_beacon.go
Labels: Improvement

#7335 [Access] Add support for multi-store reading of events, lightTransactionResults, etc. (BadgerDB & Pebble)
  cmd/access/node_builder/access_node_builder.go
  cmd/utils.go
Labels: Improvement

#7344 Remove account storage format v2 migration
  engine/execution/state/bootstrap/bootstrap_test.go
  engine/testutil/nodes.go
  fvm/accountV2Migration/AccountV2Migration.cdc
  fvm/accountV2Migration/contract.go
  fvm/accounts_test.go
  fvm/bootstrap.go
  fvm/migration/Migration.cdc
  fvm/migration/migration.go
  fvm/script.go
  fvm/systemcontracts/system_contracts.go
  fvm/transactionInvoker.go
  integration/migration/accountV2_test.go
  utils/unittest/execution_state.go
Labels: Tech Debt

#7352 [Storage] Remove unneeded lock in storage Callbacks and document it isn't safe for concurrent use
  storage/operation/badgerimpl/writer.go
  storage/operation/callbacks.go
  storage/operation/pebbleimpl/writer.go
  storage/operations.go
Labels: Performance

#7354 [Storage] Update DB.Reader() API to not return error
  cmd/execution_builder.go
  cmd/util/cmd/exec-data-json-export/delta_snapshot_exporter.go
  cmd/util/cmd/read-badger/cmd/stats.go
  engine/execution/migration/badgerpebble.go
  engine/execution/state/bootstrap/bootstrap.go
  engine/execution/state/state.go
  module/block_iterator/executor/executor_test.go
  module/block_iterator/latest/sealed_and_executed.go
  storage/mock/db.go
  storage/mock/reader.go
  storage/operation/badgerimpl/dbstore.go
  storage/operation/badgerimpl/reader.go
  storage/operation/chunk_data_packs_test.go
  storage/operation/collections_test.go
  storage/operation/commits_test.go
  storage/operation/computation_result_test.go
  storage/operation/events_test.go
  storage/operation/interactions_test.go
  storage/operation/multi_dbstore.go
  storage/operation/multi_iterator.go
  storage/operation/multi_iterator_test.go
  storage/operation/multi_reader.go
  storage/operation/multi_reader_test.go
  storage/operation/multi_seeker.go
  storage/operation/multi_seeker_test.go
  storage/operation/pebbleimpl/dbstore.go
  storage/operation/pebbleimpl/reader.go
  storage/operation/reads.go
  storage/operation/receipts_test.go
  storage/operation/results_test.go
  storage/operation/seeker_test.go
  storage/operation/stats_test.go
  storage/operation/transactions_test.go
  storage/operation/version_beacon_test.go
  storage/operations.go
  storage/store/approvals.go
  storage/store/cache_test.go
  storage/store/chunk_data_packs.go
  storage/store/chunks_queue.go
  storage/store/chunks_queue_test.go
  storage/store/collections.go
  storage/store/commits.go
  storage/store/computation_result.go
  storage/store/consumer_progress.go
  storage/store/events.go
  storage/store/light_transaction_results.go
  storage/store/my_receipts.go
  storage/store/receipts.go
  storage/store/results.go
  storage/store/transaction_result_error_messages.go
  storage/store/transaction_results.go
  storage/store/transactions.go
  storage/store/version_beacon.go
Labels: Improvement

#7361 [Storage] Support NodeDisallowList for db migration
  cmd/access/node_builder/access_node_builder.go
  cmd/observer/node_builder/observer_builder.go
  cmd/scaffold.go
  follower/follower_builder.go
  network/p2p/cache/node_disallow_list_wrapper.go
  network/p2p/cache/node_disallow_list_wrapper_test.go
  storage/node_disallow_list.go
  storage/operation/node_disallow_list.go
  storage/operation/node_disallow_list_test.go
  storage/store/node_disallow_list.go
  storage/store/node_disallow_list_test.go
Labels: Improvement

#7363 Refactor to rename blocklist to disallowlist for consistency
  cmd/access/node_builder/access_node_builder.go
  cmd/observer/node_builder/observer_builder.go
  cmd/scaffold.go
  follower/follower_builder.go
  network/p2p/cache/node_disallow_list_wrapper.go
  network/p2p/cache/node_disallow_list_wrapper_test.go
  storage/badger/operation/bft.go
  storage/badger/operation/prefix.go
  storage/operation/node_disallow_list.go
  storage/operation/prefix.go
Labels: Tech Debt
