Repository onflow/flow-go, pull requests merged in 2025-09, with the labels that each got.

#7738 Add account public key deduplication migration
  cmd/util/cmd/execution-state-extract/cmd.go
  cmd/util/ledger/migrations/account_key_deduplication_encoder.go
  cmd/util/ledger/migrations/account_key_deduplication_encoder_test.go
  cmd/util/ledger/migrations/account_key_deduplication_migration.go
  cmd/util/ledger/migrations/account_key_deduplication_migration_results.go
  cmd/util/ledger/migrations/account_key_deduplication_migration_test.go
  cmd/util/ledger/migrations/account_key_deduplication_migration_utils.go
  cmd/util/ledger/migrations/cadence_value_diff.go
  cmd/util/ledger/migrations/storage_used_migration.go
  cmd/util/ledger/migrations/storage_used_migration_test.go
  cmd/util/ledger/util/registers/registers.go
  engine/execution/state/bootstrap/bootstrap_test.go
  fvm/environment/accounts.go
  fvm/environment/accounts_status.go
  go.mod
  model/flow/account_encoder.go
  model/flow/account_encoder_test.go
  model/flow/ledger.go
  utils/unittest/execution_state.go
Labels: enhancement, Performance

#7793 Add support for tracing to debug-tx command
  cmd/util/cmd/debug-tx/cmd.go
  go.mod
  go.sum
  module/mock/tracer.go
  module/trace/noop.go
  module/trace/trace.go
  module/tracer.go
  utils/debug/remoteDebugger.go
Labels: Feature

#7817 Bump `ethereum/go-ethereum` dependency to `v1.16.3`
  fvm/evm/emulator/emulator.go
  fvm/evm/emulator/emulator_test.go
  fvm/evm/emulator/tracker.go
  fvm/evm/precompiles/arch.go
  fvm/evm/precompiles/precompile.go
  fvm/evm/precompiles/replayer.go
  fvm/evm/testutils/handler.go
  go.mod
  go.sum
  insecure/go.mod
  insecure/go.sum
  integration/go.mod
  integration/go.sum
Labels: Flow EVM

#7829 Add runtime public key duplicate detection and storage with support for account status v4 format
  cmd/util/ledger/migrations/account_key_deduplication_encoder.go
  cmd/util/ledger/migrations/account_key_deduplication_encoder_test.go
  cmd/util/ledger/migrations/storage_used_migration.go
  cmd/util/ledger/util/payload_file_test.go
  engine/execution/state/bootstrap/bootstrap_test.go
  fvm/environment/account-key-metadata/digest.go
  fvm/environment/account-key-metadata/digest_test.go
  fvm/environment/account-key-metadata/encoder_util.go
  fvm/environment/account-key-metadata/key_index_mapping_group.go
  fvm/environment/account-key-metadata/key_index_mapping_group_test.go
  fvm/environment/account-key-metadata/metadata.go
  fvm/environment/account-key-metadata/metadata_test.go
  fvm/environment/account-key-metadata/weight_and_revoked_group.go
  fvm/environment/account-key-metadata/weight_and_revoked_group_test.go
  fvm/environment/account_key_updater.go
  fvm/environment/account_key_updater_test.go
  fvm/environment/account_public_key_util.go
  fvm/environment/account_public_key_util_export_test.go
  fvm/environment/account_public_key_util_test.go
  fvm/environment/accounts.go
  fvm/environment/accounts_status.go
  fvm/environment/accounts_status_test.go
  fvm/environment/accounts_test.go
  fvm/environment/mock/accounts.go
  fvm/errors/account_key.go
  fvm/errors/codes.go
  fvm/transactionSequenceNum.go
  model/flow/ledger.go
  model/flow/ledger_test.go
  utils/unittest/execution_state.go
Labels: Breaking Change, Performance

#7737 [Flow EVM] Handle non-existing accounts in all of state overrides methods
  fvm/evm/emulator/state/base.go
  fvm/evm/offchain/query/view.go
  fvm/evm/offchain/query/view_test.go
Labels: Bugfix, Flow EVM

#7025 backport tx error messages to v0.37.12
  admin/README.md
  admin/commands/storage/backfill_tx_error_messages.go
  admin/commands/storage/backfill_tx_error_messages_test.go
  admin/commands/storage/read_blocks_test.go
  admin/commands/storage/read_results_test.go
  cmd/access/node_builder/access_node_builder.go
  cmd/util/cmd/common/node_info.go
  engine/access/access_test.go
  engine/access/ingestion/engine.go
  engine/access/ingestion/engine_test.go
  engine/access/ingestion/tx_error_messages/tx_error_messages_core.go
  engine/access/ingestion/tx_error_messages/tx_error_messages_core_test.go
  engine/access/ingestion/tx_error_messages/tx_error_messages_engine.go
  engine/access/ingestion/tx_error_messages/tx_error_messages_engine_test.go
  engine/access/rpc/backend/backend.go
  engine/access/rpc/backend/backend_accounts.go
  engine/access/rpc/backend/backend_accounts_test.go
  engine/access/rpc/backend/backend_events.go
  engine/access/rpc/backend/backend_events_test.go
  engine/access/rpc/backend/backend_scripts.go
  engine/access/rpc/backend/backend_scripts_test.go
  engine/access/rpc/backend/backend_stream_blocks_test.go
  engine/access/rpc/backend/backend_stream_transactions_test.go
  engine/access/rpc/backend/backend_test.go
  engine/access/rpc/backend/backend_transactions.go
  engine/access/rpc/backend/backend_transactions_test.go
  engine/access/rpc/backend/node_selector.go
  engine/access/rpc/backend/transactions_local_data_provider.go
  engine/common/grpc/forwarder/forwarder.go
  engine/common/rpc/utils.go
  engine/errors.go
  integration/tests/access/cohort3/access_store_tx_error_messages_test.go
  model/flow/transaction_result.go
  module/jobqueue.go
  module/metrics/labels.go
  storage/all.go
  storage/badger/operation/prefix.go
  storage/badger/operation/transaction_results.go
  storage/badger/transaction_result_error_messages.go
  storage/badger/transaction_result_error_messages_test.go
  storage/mock/transaction_result_error_messages.go
  storage/transaction_results.go
  utils/unittest/logging.go
  utils/unittest/mocks/closer.go
Labels: Stale

#7925 Support account status v4 in checkpoint-collect-stats util
  cmd/util/cmd/checkpoint-collect-stats/cmd.go
Labels: Improvement

#7917 Update storage health check to add account key validation, etc.
  cmd/util/cmd/check-storage/cmd.go
  cmd/util/ledger/migrations/account_key_deduplication_migration.go
  cmd/util/ledger/migrations/account_key_deduplication_migration_test.go
  cmd/util/ledger/migrations/account_key_deduplication_migration_validation.go
Labels: Improvement

#7936 Prevent actions/stale from closing pull requests with "Preserve" label
  .github/workflows/stale.yml
Labels: Bugfix

#7597 [Storage] Fix memory caches getting out of sync with db (BadgerDB & Pebble)
  cmd/execution_builder.go
  cmd/util/cmd/read-badger/cmd/transaction_results.go
  cmd/util/cmd/rollback-executed-height/cmd/rollback_executed_height.go
  cmd/util/cmd/rollback-executed-height/cmd/rollback_executed_height_test.go
  engine/testutil/nodes.go
  go.mod
  go.sum
  insecure/go.mod
  insecure/go.sum
  integration/go.mod
  integration/go.sum
  storage/mock/batch.go
  storage/mock/reader_batch_writer.go
  storage/operation/badgerimpl/writer.go
  storage/operation/pebbleimpl/writer.go
  storage/operation/writes_test.go
  storage/operations.go
  storage/store/cache.go
  storage/store/cache_test.go
  storage/store/group_cache.go
  storage/store/group_cache_test.go
  storage/store/transaction_results.go
  storage/store/transaction_results_test.go
Labels: Bugfix
