Repository onflow/flow-go, pull requests merged in 2025-03, with the labels that each got.

#7125 [Storage] Fix InitBadgerAndPebble() not closing badger.DB on error
  cmd/util/cmd/read-badger/cmd/storages.go
Labels: Bugfix

#6838 Introduce the `dryCall` method under `EVM` contract & `CadenceOwnedAccount` resource
  engine/execution/state/bootstrap/bootstrap_test.go
  fvm/evm/evm_test.go
  fvm/evm/impl/impl.go
  fvm/evm/stdlib/contract.cdc
  fvm/evm/stdlib/contract.go
  fvm/evm/stdlib/contract_test.go
  utils/unittest/execution_state.go
Labels: Feature, Flow EVM

#7153 [Storage] Release Pebble batch resource to reduce memory use
  storage/operation/pebbleimpl/writer.go
Labels: Improvement
